### ISSUE TITLE
Framing error, unexpected byte: 63

### ISSUE THREAD

**Issue by cozyvision** [php-amqplib/php-amqplib#1036]
**Version(s) affected**: 3.2.0

**Description**  
"Framing error, unexpected byte: 63"
```
[hex]:
0000  41 4D 51 50 00 00 09 01                            AMQP....

waiting for 10,10
waiting for a new frame
closing input
closing socket
Framing error, unexpected byte: 63
#0 /var/www/html/rabbitmq/app/Vendor/PhpAmqpLib/Connection/AbstractConnection.php(658): PhpAmqpLib\Connection\AbstractConnection->wait_frame()
#1 /var/www/html/rabbitmq/app/Vendor/PhpAmqpLib/Channel/AbstractChannel.php(234): PhpAmqpLib\Connection\AbstractConnection->wait_channel()
#2 /var/www/html/rabbitmq/app/Vendor/PhpAmqpLib/Channel/AbstractChannel.php(351): PhpAmqpLib\Channel\AbstractChannel->next_frame()
#3 /var/www/html/rabbitmq/app/Vendor/PhpAmqpLib/Connection/AbstractConnection.php(266): PhpAmqpLib\Channel\AbstractChannel->wait()
#4 /var/www/html/rabbitmq/app/Vendor/PhpAmqpLib/Connection/AbstractConnection.php(237): PhpAmqpLib\Connection\AbstractConnection->connect()
#5 /var/www/html/rabbitmq/app/Vendor/PhpAmqpLib/Connection/AMQPStreamConnection.php(64): PhpAmqpLib\Connection\AbstractConnection->__construct()
#6 /var/www/html/rabbitmq/app/Console/Command/Task/ProcessSmtpTask.php(56): 
```

**Comment by ramunasd** [comment]
Very likely You are connecting to wrong port/service.

**Comment by cozyvision** [comment]
i tried to enter some other(wrong) IP and port combination.

Wrong IP
`stream_socket_client(): Unable to connect to tcp://10.8.0.1:5672 (Connection timed out)`
Wrong Port
`stream_socket_client(): Unable to connect to tcp://127.0.0.1:56727 (Connection refused)`

But with the right IP and port(i am using the same IP,port, username and password in my java code and its working from the same server).

**Comment by ramunasd** [comment]
Any errors in rabbitmq logs?

**Comment by cozyvision** [comment]
RabbitMQ logs "client unexpectedly closed TCP connection"

```
2022-10-25 11:57:13.586152+00:00 [info] <0.28585.0> accepting AMQP connection <0.28585.0> (127.0.0.1:44438 -> 127.0.0.1:5672)
2022-10-25 11:57:13.588942+00:00 [warning] <0.28585.0> closing AMQP connection <0.28585.0> (127.0.0.1:44438 -> 127.0.0.1:5672):
2022-10-25 11:57:13.588942+00:00 [warning] <0.28585.0> client unexpectedly closed TCP connection
```
