### ISSUE TITLE
`AMQPTimeoutException` is thrown without reaching the timeout limit

### ISSUE THREAD

**Issue by mrtus** [php-amqplib/php-amqplib#1109]
Hello 👋 

We've been encountering a very mysterious issue between the versions `v3.5.2` and [`v3.5.3`](https://github.com/php-amqplib/php-amqplib/releases/tag/v3.5.3).
Our client heartbeat is configured on 30 seconds and our server heartbeat is configured on 60 seconds, the connection timeout on the client is configured on 3 seconds.

Exception stacktrace:
```
PhpAmqpLib\Exception\AMQPTimeoutException: The connection timed out after 30 sec while awaiting incoming data
#58 /composer/php-amqplib/php-amqplib/PhpAmqpLib/Wire/AMQPIOReader.php(102): PhpAmqpLib\Wire\AMQPIOReader::wait
#57 /composer/php-amqplib/php-amqplib/PhpAmqpLib/Wire/AMQPIOReader.php(60): PhpAmqpLib\Wire\AMQPIOReader::rawread
#56 /composer/php-amqplib/php-amqplib/PhpAmqpLib/Wire/AMQPReader.php(346): PhpAmqpLib\Wire\AMQPReader::readFrameHeader
#55 /composer/php-amqplib/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php(597): PhpAmqpLib\Connection\AbstractConnection::wait_frame
#54 /composer/php-amqplib/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php(654): PhpAmqpLib\Connection\AbstractConnection::wait_channel
#53 /composer/php-amqplib/php-amqplib/PhpAmqpLib/Channel/AbstractChannel.php(232): PhpAmqpLib\Channel\AbstractChannel::next_frame
#52 /composer/php-amqplib/php-amqplib/PhpAmqpLib/Channel/AbstractChannel.php(341): PhpAmqpLib\Channel\AbstractChannel::wait
```

`AbstractChannel::wait`  is called with a timeout value of 30 seconds.

---

With the upgrade `AMQPTimeoutException` started occuring so much more, from about 10-times a day actually legit occurrences to >3K times a day where the exception is thrown already after 1-3 seconds, which is less than the 30s timeout or 30s heartbeat configured.

From what I am understanding, this exception can only be thrown when `stream_select` returns `false`.
We do not understand which scenarios would result in the IO method returning `false`.

From the PHP documentation it could be interrupted by signals, however we have logging in place and at all those exception occurrences there is never a SIGNAL that interrupts the stream socket.

Because of this issue we have not been able to upgrade the library to `v3.5.3`.

Now we have upgraded our RabbitMQ cluster instances from `v3.10.x` to `v3.12.x` and are encountering the exact same problem and exact same behaviour as we observed with the library `v3.5.3` upgrade.

Once we noticed this behaviour on an upgrade cluster we upgraded the library in the hopes this would resolve it, however, it did not. The library upgrade also did not create more problems than were already occuring after the cluster upgrade, so somehow the initial library upgrade its issues are "nullified".

This scenario only occurs in a temporary queue (RPC) environment where the exception is thrown while waiting for a message/response on the temporary queue.

---

Would someone be able to tell us:
- How to investigate this further, or be able to tell us how the versions `v3.5.2` and `v3.5.3` changes could actually cause this behaviour?
- Which scenarios result in `stream_select` returning `false`?
- Is there more information we could provide you with to help you better understand this behaviour?
- How can such a small bugfix cause so many problems for us after only [`$v > 0` was added](https://github.com/php-amqplib/php-amqplib/pull/1081) to an if-clause, where the result seemingly would not affect us because the heartbeat would stay on the same 30 seconds.

We are eager to hear back on this.

Thank you in advance!

**Comment by mrtus** [comment]
Appologies, this seems to be almost a similar case to https://github.com/php-amqplib/php-amqplib/issues/1101 I think? 🤔

**Comment by ramunasd** [comment]
In 30 seconds there was no messages from broker. Basically Your queue is empty.
The normal practice is to catch exception and try again or proceed with another queue.

**Comment by mrtus** [comment]
> In 30 seconds there was no messages from broker. Basically Your queue is empty. The normal practice is to catch exception and try again or proceed with another queue.

Yes, however, 30 seconds is not the period that passed, only 1-3 seconds passes and the exception occurs already.
And this is really confusing for us, especially since this can't be simply caused by a small bugfix in the library, yet it does change the behaviour of this scenario 😟.

Unfortunately we cannot reproduce this scenario either.

How can I help you understand our problem better @ramunasd ?

**Comment by mrtus** [comment]
I also want to point out that I have followed the conclusion from https://github.com/php-amqplib/php-amqplib/issues/1101 by adding a RPC timeout value higher than zero, and this is now giving us the same failures, where the RPC timeout value is 40s but it already starts failing after 1-3 seconds.

So there seems to be something wrong with the timeout handling somewhere.

**Comment by ramunasd** [comment]
We need more information about how to reproduce it. Connection parameters, full stack trace and way to reproduce issue would be nice to have. Also, whole output from `tests/phpinfo.php`.

**Comment by mrtus** [comment]
Appologies for the late reply.

We were able to resolve our issues by looping `Channel->wait(null, false, 5)` and introducing our own 30s "timout" next to it.

We also noticed some similar behaviour with `stream_select` timing out again on `Channel->queue_declare('')` returning a `null`. So we are now generating those random queue names ourselves, instead of offloading that task to the RabbitMQ cluster.

Next to that we introduced AMQProxy to our stack to mitigate further random `stream_select` failures and thus improve networking stability for AMQP and the constant open & close of channels to facilitate the RPC behaviour.

Based on that, I suggest we close this issue.

Though, it is still a mystery to us why those `stream_select` failures suddenly started happening because of a simple AMQP-lib bump.

Thank you for the help @ramunasd.
