### ISSUE TITLE
Regression in v2.2.3: Time out

### ISSUE THREAD

**Issue by mnapoli** [php-amqplib/php-amqplib#128]
Hi!

I've upgraded from 2.2.2 to 2.2.3 this morning, and all our workers are now crashing:

```
PhpAmqpLib\Exception\AMQPTimeoutException: Error reading data. Socket connection timed out
at /.../vendor/videlalvaro/php-amqplib/PhpAmqpLib/Wire/IO/StreamIO.php(46)
#0 /.../vendor/videlalvaro/php-amqplib/PhpAmqpLib/Wire/AMQPReader.php(128): PhpAmqpLib\Wire\IO\StreamIO->read(7)
#1 /.../vendor/videlalvaro/php-amqplib/PhpAmqpLib/Wire/AMQPReader.php(88): PhpAmqpLib\Wire\AMQPReader->rawread(7)
#2 /.../vendor/videlalvaro/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php(311): PhpAmqpLib\Wire\AMQPReader->read(7)
#3 /.../vendor/videlalvaro/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php(344): PhpAmqpLib\Connection\AbstractConnection->wait_frame(0)
#4 /.../vendor/videlalvaro/php-amqplib/PhpAmqpLib/Channel/AbstractChannel.php(121): PhpAmqpLib\Connection\AbstractConnection->wait_channel(1, 0)
#5 /.../vendor/videlalvaro/php-amqplib/PhpAmqpLib/Channel/AbstractChannel.php(229): PhpAmqpLib\Channel\AbstractChannel->next_frame(0)
#6 /.../vendor/myclabs/work/src/MyCLabs/Work/Worker/RabbitMQWorker.php(51): PhpAmqpLib\Channel\AbstractChannel->wait()
#7 /.../scripts/jobs/work/work.php(27): MyCLabs\Work\Worker\RabbitMQWorker->work(1)
#8 {main}
```

FYI here is the `work` function: [RabbitMQWorker.php#L40](https://github.com/myclabs/Work/blob/master/src/MyCLabs/Work/Worker/RabbitMQWorker.php#L40).

**Comment by postalservice14** [comment]
Is this still an issue?

**Comment by mnapoli** [comment]
I have no idea, I do not maintain that software anymore. This issue can be closed I guess.
