### ISSUE TITLE
if connect to the port is not Rabbitmq-server's port. There may be caused by PHP memory exhausted

### ISSUE THREAD

**Issue by rannk** [php-amqplib/php-amqplib#220]
I accidentally set the port as 22(there has SSH service). The program will has the memory exhausted 
error.
error like this:
PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 758263345 bytes) in /home/test/rabbitmq_receive/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Wire/IO/StreamIO.php on line 43
 although I set the php memory limit as 1G or more. The issue still exists. when I change port back. That issue will missing.

suggestion author to check the socket read function, maybe the type of service without judgment.

**Comment by lukebakken** [comment]
This is what I get when I try to connect to `sshd` locally using the `demo/amqp_consumer.php` script:

```
lbakken@shostakovich ~/development/php-amqplib/php-amqplib/demo (master *=)
$ php ./amqp_consumer.php 
< [hex]: 
0000  41 4D 51 50 00 00 09 01                            AMQP.... 

waiting for 10,10
waiting for a new frame
PHP Fatal error:  Uncaught PhpAmqpLib\Exception\AMQPRuntimeException: Invalid frame type 83 in /home/lbakken/development/php-amqplib/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php:525
Stack trace:
#0 /home/lbakken/development/php-amqplib/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php(566): PhpAmqpLib\Connection\AbstractConnection->wait_frame(3)
#1 /home/lbakken/development/php-amqplib/php-amqplib/PhpAmqpLib/Channel/AbstractChannel.php(217): PhpAmqpLib\Connection\AbstractConnection->wait_channel(0, 3)
#2 /home/lbakken/development/php-amqplib/php-amqplib/PhpAmqpLib/Channel/AbstractChannel.php(327): PhpAmqpLib\Channel\AbstractChannel->next_frame(3)
#3 /home/lbakken/development/php-amqplib/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php(211): PhpAmqpLib\Channel\AbstractChannel->wait(Array, false, 3)
#4 /home/lbakken/development/php-amqplib/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php(186): PhpAmqpLib\Connection\AbstractConnection->connect()
#5 /home/lbakken/development/php-amqplib/php-amqpl in /home/lbakken/development/php-amqplib/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php on line 525
```
