### ISSUE TITLE
leaking exception? uncaught exception after catching it

### ISSUE THREAD

**Issue by rocksfrow** [php-amqplib/php-amqplib#223]
OK, so using 2.4.1 (latest release), I am finding it impossible to avoid my script from dieing via an uncaught exception, even though I am catching it and closing execution immediately after.

As you can see below, I've wrapped my wait to catch the amqpruntimeexception and immediately exit(), just like the timeout exception.

If I set an idle timeout, I am able to catch the AMQPTimeoutException and exit JUST FINE... but the AMQPRuntimeException is throwing me for a loop.

```
while (count($ch->callbacks)) {
  try {
    $ch->wait(null, false, AMQP_IDLETIMEOUT);
  } catch (PhpAmqpLib\Exception\AMQPTimeoutException $e) {
    echo "idle timeout, exiting...\n";
    exit();
  } catch (PhpAmqpLib\Exception\AMQPRuntimeException $e) {
    echo "caught runtime exception, exiting...\n";
    exit();
  } 
}
```

With the above code, after the script is running for quite some time (presumably due to network issue?)

My goal is to catch this exception, clear the connection/reconnect, and retry. BUT, I cannot even get that far as I can't reliably catch the exception.

As you can see, my echo 'caught runtime exception' triggered, but before the script is able to exit it looks like a separate AMQPRuntimeException occurs?

Is there another way I should go about capturing this, or is this a bug as I suspect?

Here is output:

```
caught runtime exception, exiting...
PHP Fatal error:  Uncaught exception 'PhpAmqpLib\Exception\AMQPRuntimeException' with message 'Broken pipe or closed connection' in /home/ninja/ninja/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Wire/IO/StreamIO.php:174
Stack trace:
#0 /home/ninja/ninja/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php(387): PhpAmqpLib\Wire\IO\StreamIO->write('\x01\x00\x01\x00\x00\x00\v\x00\x14\x00(\x00\x00\x00\x00...')
#1 /home/ninja/ninja/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php(498): PhpAmqpLib\Connection\AbstractConnection->write('\x01\x00\x01\x00\x00\x00\v\x00\x14\x00(\x00\x00\x00\x00...')
#2 /home/ninja/ninja/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Channel/AbstractChannel.php(191): PhpAmqpLib\Connection\AbstractConnection->send_channel_method_frame(1, Array, Object(PhpAmqpLib\Wire\AMQPWriter))
#3 /home/ninja/ninja/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Channel/AMQPChannel.php(199): PhpAmqpLib\Channel\AbstractChannel->send_method_frame(Array, Object(PhpAmqpLib\Wire\AMQPWriter) in /home/ninja/ninja/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Wire/IO/StreamIO.php on line 174
```

**Comment by jayeshneema** [comment]
I am getting the following error: 


$ php send.php
PHP Fatal error:  Uncaught exception 'PhpAmqpLib\Exception\AMQPRuntimeException' with message 'Error Connecting to server (113): No route to host' in /opt/lampp/htdocs/rabbit/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Wire/IO/StreamIO.php:106
Stack trace:
#0 /opt/lampp/htdocs/rabbit/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php(195): PhpAmqpLib\Wire\IO\StreamIO->connect()
#1 /opt/lampp/htdocs/rabbit/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php(179): PhpAmqpLib\Connection\AbstractConnection->connect()
#2 /opt/lampp/htdocs/rabbit/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Connection/AMQPStreamConnection.php(41): PhpAmqpLib\Connection\AbstractConnection->__construct('guest', 'guest', '/', false, 'AMQPLAIN', NULL, 'en_US', Object(PhpAmqpLib\Wire\IO\StreamIO), 0)
#3 /opt/lampp/htdocs/rabbit/send.php(7): PhpAmqpLib\Connection\AMQPStreamConnection->__construct('localhost', 5672, 'guest', 'guest')
#4 {main}
  thrown in /opt/lampp/htdocs/rabbit/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Wire/IO/StreamIO.php on line 106

**Comment by ravindrakhokharia** [comment]
Any suggestions on the below please ?

[2015-10-22 16:58:50] app.ERROR: Exception Occured. Exception:PhpAmqpLib\Exception\AMQPRuntimeException [] []
[2015-10-22 16:58:50] request.CRITICAL: Uncaught PHP Exception PhpAmqpLib\Exception\AMQPRuntimeException: "Error Connecting to server (110): Connection timed out" at /var/www/project/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Wire/IO/StreamIO.php line 106 {"exception":"[object] (PhpAmqpLib\\Exception\\AMQPRuntimeException: Error Connecting to server (110): Connection timed out at /var/www/project/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Wire/IO/StreamIO.php:106)"} []

**Comment by michaelklishin** [comment]
@ravindrakhokharia the client couldn't connect to RabbitMQ: connection timed out.

**Comment by ravindrakhokharia** [comment]
@michaelklishin Any suggestions how can i recover/handle that, and re connect ?

**Comment by till** [comment]
@ravindrakhokharia verify the settings you use to connect to RabbitMQ and maybe your network after. The error message is in what you pasted, "Connection timed out". Google that up or hire someone.

**Comment by acpmasquerade** [comment]
Its seems to be weird case. If celery isn't running in background and exception is handled, the exception propagates through and everything else below the code starts to behave something else.

Its even violates the error_reporting definition and starts to throw exception even on E_WARN and E_NOTICE cases.

**Comment by lukebakken** [comment]
Closing due to inactivity.
