### ISSUE TITLE
Error in running the demo file

### ISSUE THREAD

**Issue by pushpesh4u** [php-amqplib/php-amqplib#260]
I am trying to run this - https://github.com/videlalvaro/php-amqplib/blob/master/demo/amqp_publisher_exclusive.php

Lines 26/27 give an error below:

```
PHP Fatal error:  Uncaught exception 'PhpAmqpLib\Exception\AMQPProtocolConnectionException' with message 'UNEXPECTED_FRAME - expected method frame, got non method frame instead' in /var/www/html/rabbitmq/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php:680
Stack trace:
#0 [internal function]: PhpAmqpLib\Connection\AbstractConnection->connection_close(Object(PhpAmqpLib\Wire\AMQPReader))
#1 /var/www/html/rabbitmq/php-amqplib/PhpAmqpLib/Channel/AbstractChannel.php(178): call_user_func(Array, Object(PhpAmqpLib\Wire\AMQPReader))
#2 /var/www/html/rabbitmq/php-amqplib/PhpAmqpLib/Channel/AbstractChannel.php(370): PhpAmqpLib\Channel\AbstractChannel->dispatch('10,50', '??FUNEXPECTED_F...', NULL)
#3 /var/www/html/rabbitmq/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php(583): PhpAmqpLib\Channel\AbstractChannel->wait()
#4 /var/www/html/rabbitmq/php-amqplib/PhpAmqpLib/Channel/AbstractChannel.php(198): PhpAmqpLib\Connection\AbstractConnection->wait_channel(1, 0)
#5 /var/www/html/rabbitmq/php-amqplib/PhpAmqpLib/Channel/Abstra in /var/www/html/rabbitmq/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php on line 680

```

If I comment the 2 lines, it works.

**Comment by videlalvaro** [comment]
Any logs on the RabbitMQ logs when you see this?

**Comment by pwarnock** [comment]
/usr/local/var/log/rabbitmq/rabbit@localhost.log
```
=INFO REPORT==== 24-Jun-2015::11:50:23 ===
accepting AMQP connection <0.442.0> (127.0.0.1:60973 -> 127.0.0.1:5672)

=ERROR REPORT==== 24-Jun-2015::11:50:23 ===
Error on AMQP connection <0.442.0> (127.0.0.1:60973 -> 127.0.0.1:5672, vhost: '/', user: 'guest', state: running), channel 1:
{amqp_error,unexpected_frame,
            "expected method frame, got non method frame instead",none}

=INFO REPORT==== 24-Jun-2015::11:50:23 ===
closing AMQP connection <0.442.0> (127.0.0.1:60973 -> 127.0.0.1:5672)
```
output with lines commented out:
```
< [hex]: 
0000  41 4D 51 50 00 00 09 01                            AMQP.... 

waiting for 10,10
waiting for a new frame
> 10,10: Connection.start
Start from server, version: 0.9, properties: capabilities=(publisher_confirms=1, exchange_exchange_bindings=1, basic.nack=1, consumer_cancel_notify=1, connection.blocked=1, consumer_priorities=1, authentication_failure_close=1, per_consumer_qos=1), cluster_name=rabbit@Peters-MacBook-Pro, copyright=Copyright (C) 2007-2014 GoPivotal, Inc., information=Licensed under the MPL.  See http://www.rabbitmq.com/, platform=Erlang/OTP, product=RabbitMQ, version=3.5.3, mechanisms: AMQPLAIN, PLAIN, locales: en_US
< 10,11: Connection.start_ok
< [hex]: 
0000  01 00 00 00 00 01 31 00  0A 00 0B 00 00 00 F3 07   ......1. ......Û.
0010  70 72 6F 64 75 63 74 53  00 00 00 07 41 4D 51 50   productS ....AMQP
0020  4C 69 62 08 70 6C 61 74  66 6F 72 6D 53 00 00 00   Lib.plat formS...
0030  03 50 48 50 07 76 65 72  73 69 6F 6E 53 00 00 00   .PHP.ver sionS...
0040  03 32 2E 34 0B 69 6E 66  6F 72 6D 61 74 69 6F 6E   .2.4.inf ormation
0050  53 00 00 00 00 09 63 6F  70 79 72 69 67 68 74 53   S.....co pyrightS
0060  00 00 00 00 0C 63 61 70  61 62 69 6C 69 74 69 65   .....cap abilitie
0070  73 46 00 00 00 8C 1C 61  75 74 68 65 6E 74 69 63   sF...å.a uthentic
0080  61 74 69 6F 6E 5F 66 61  69 6C 75 72 65 5F 63 6C   ation_fa ilure_cl
0090  6F 73 65 74 01 12 70 75  62 6C 69 73 68 65 72 5F   oset..pu blisher_
00A0  63 6F 6E 66 69 72 6D 73  74 01 16 63 6F 6E 73 75   confirms t..consu
00B0  6D 65 72 5F 63 61 6E 63  65 6C 5F 6E 6F 74 69 66   mer_canc el_notif
00C0  79 74 01 1A 65 78 63 68  61 6E 67 65 5F 65 78 63   yt..exch ange_exc
00D0  68 61 6E 67 65 5F 62 69  6E 64 69 6E 67 73 74 01   hange_bi ndingst.
00E0  0A 62 61 73 69 63 2E 6E  61 63 6B 74 01 12 63 6F   .basic.n ackt..co
00F0  6E 6E 65 63 74 69 6F 6E  2E 62 6C 6F 63 6B 65 64   nnection .blocked
0100  74 01 08 41 4D 51 50 4C  41 49 4E 00 00 00 23 05   t..AMQPL AIN...#.
0110  4C 4F 47 49 4E 53 00 00  00 05 67 75 65 73 74 08   LOGINS.. ..guest.
0120  50 41 53 53 57 4F 52 44  53 00 00 00 05 67 75 65   PASSWORD S....gue
0130  73 74 05 65 6E 5F 55 53  CE                        st.en_US Œ

< 10,11: Connection.start_ok
waiting for 10,20, 10,30
waiting for a new frame
> 10,30: Connection.tune
< 10,31: Connection.tune_ok
< [hex]: 
0000  01 00 00 00 00 00 0C 00  0A 00 1F FF FF 00 02 00   ........ ...ˇˇ...
0010  00 00 00 CE                                        ...Œ

< 10,31: Connection.tune_ok
< 10,40: Connection.open
< [hex]: 
0000  01 00 00 00 00 00 08 00  0A 00 28 01 2F 00 00 CE   ........ ..(./..Œ

< 10,40: Connection.open
waiting for 10,41
waiting for a new frame
> 10,41: Connection.open_ok
Open OK! known_hosts: 
using channel_id: 1
< 20,10: Channel.open
< [hex]: 
0000  01 00 01 00 00 00 05 00  14 00 0A 00 CE            ........ ....Œ

< 20,10: Channel.open
waiting for 20,11
waiting for a new frame
> 20,11: Channel.open_ok
Channel open
< 40,10: Exchange.declare
< [hex]: 
0000  01 00 01 00 00 00 34 00  28 00 0A 00 00 21 66 61   ......4. (....!fa
0010  6E 6F 75 74 5F 65 78 63  6C 75 73 69 76 65 5F 65   nout_exc lusive_e
0020  78 61 6D 70 6C 65 5F 65  78 63 68 61 6E 67 65 06   xample_e xchange.
0030  66 61 6E 6F 75 74 04 00  00 00 00 CE               fanout.. ...Œ

< 40,10: Exchange.declare
waiting for 40,11
waiting for a new frame
> 40,11: Exchange.declare_ok
< 60,40: Basic.publish
< [hex]: 
0000  01 00 01 00 00 00 2A 00  3C 00 28 00 00 21 66 61   ......*. <.(..!fa
0010  6E 6F 75 74 5F 65 78 63  6C 75 73 69 76 65 5F 65   nout_exc lusive_e
0020  78 61 6D 70 6C 65 5F 65  78 63 68 61 6E 67 65 00   xample_e xchange.
0030  00 CE 02 00 01 00 00 00  19 00 3C 00 00 00 00 00   .Œ...... ..<.....
0040  00 00 00 00 00 80 00 0A  74 65 78 74 2F 70 6C 61   .....Ä.. text/pla
0050  69 6E CE 03 00 01 00 00  00 00 CE                  inŒ..... ..Œ

< 20,40: Channel.close
< [hex]: 
0000  01 00 01 00 00 00 0B 00  14 00 28 00 00 00 00 00   ........ ..(.....
0010  00 00 CE                                           ..Œ

< 20,40: Channel.close
waiting for 20,41
waiting for a new frame
waiting for any method
waiting for a new frame
> 10,50: Connection.close
< 10,51: Connection.close_ok
< [hex]: 
0000  01 00 00 00 00 00 04 00  0A 00 33 CE               ........ ..3Œ

< 10,51: Connection.close_ok
closing input
closing socket
< 10,50: Connection.close
< [hex]: 
0000  01 00 00 00 00 00 0B 00  0A 00 32 00 00 00 00 00   ........ ..2.....
0010  00 00 CE                                           ..Œ

```

**Comment by michaelklishin** [comment]
@pwarnock can you post a libpcap capture (e.g. Wireshark)?

**Comment by nubeiro** [comment]
Is this still an issue?

**Comment by postalservice14** [comment]
If this is still an issue...  Are you using the default connection configuration?  User: guest, Pass: guest, VHOST: '/', etc...?  Or did you change anything in `demo/config.php`?

I've seen this happen if the vhost, or user/pass is incorrect.

**Comment by lukebakken** [comment]
Closing due to inactivity.
