### ISSUE TITLE
AMQPProtocolConnectionException: FRAME_ERROR - cannot decode <<0,0,0,0,65,114,114,97,121,0>>

### ISSUE THREAD

**Issue by pinepain** [php-amqplib/php-amqplib#266]
Hi,

I was dealing with [direct reply-to](http://www.rabbitmq.com/direct-reply-to.html) support in [php-amqp](https://github.com/pdezwart/php-amqp) and used your lib to make proof of conecept (see https://groups.google.com/forum/#!topic/rabbitmq-users/wHYwE6DKuKE discussion). Apart from that I initially didn't get properly fast-reply forkflow, looks like php-amqplib has some bug (or I did something wrong?).

The code below

``` php
<?php
require "vendor/autoload.php";

use PhpAmqpLib\Message\AMQPMessage;

$conn = new \PhpAmqpLib\Connection\AMQPStreamConnection(
    'localhost',
    5672,
    'guest',
    'guest'
);
$channel = $conn->channel();

// Establish connection, create a channel...
$callback_queue = 'amq.rabbitmq.reply-to';

$response = null;
$channel->basic_consume($callback_queue, '', false, true, false, false, function (AMQPMessage $message) use (&$response) {
    echo $message->body . PHP_EOL;
    $response = true;
});


$reqest_queue = $channel->queue_declare();

$msg = new AMQPMessage('request', ['reply_to' => $callback_queue]);

var_dump($msg);


$channel->basic_publish($msg, '', $reqest_queue);

$req_message = $channel->basic_get($reqest_queue, true);

var_dump($req_message);
```

yields me a huge stacktrace:

```
vagrant@vagrant-ubuntu-utopic-64 (php:5.6.4 -phpbrew):~/php-amqp$ php test-amqplib.php 
class PhpAmqpLib\Message\AMQPMessage#20 (6) {
  public $body =>
  string(7) "request"
  public $content_encoding =>
  NULL
  public $delivery_info =>
  array(0) {
  }
  protected $prop_types =>
  array(14) {
    'content_type' =>
    string(8) "shortstr"
    'content_encoding' =>
    string(8) "shortstr"
    'application_headers' =>
    string(12) "table_object"
    'delivery_mode' =>
    string(5) "octet"
    'priority' =>
    string(5) "octet"
    'correlation_id' =>
    string(8) "shortstr"
    'reply_to' =>
    string(8) "shortstr"
    'expiration' =>
    string(8) "shortstr"
    'message_id' =>
    string(8) "shortstr"
    'timestamp' =>
    string(9) "timestamp"
    'type' =>
    string(8) "shortstr"
    'user_id' =>
    string(8) "shortstr"
    'app_id' =>
    string(8) "shortstr"
    'cluster_id' =>
    string(8) "shortstr"
  }
  private $properties =>
  array(1) {
    'reply_to' =>
    string(21) "amq.rabbitmq.reply-to"
  }
  private $serialized_properties =>
  NULL
}
PHP Notice:  Array to string conversion in /home/vagrant/php-amqp/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Channel/AMQPChannel.php on line 1050
PHP Stack trace:
PHP   1. {main}() /home/vagrant/php-amqp/test-amqplib.php:0
PHP   2. PhpAmqpLib\Channel\AMQPChannel->basic_publish() /home/vagrant/php-amqp/test-amqplib.php:32
PHP   3. PhpAmqpLib\Channel\AMQPChannel->pre_publish() /home/vagrant/php-amqp/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Channel/AMQPChannel.php:1092
PHP   4. sprintf() /home/vagrant/php-amqp/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Channel/AMQPChannel.php:1050

Notice: Array to string conversion in /home/vagrant/php-amqp/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Channel/AMQPChannel.php on line 1050

Call Stack:
    0.0007     244904   1. {main}() /home/vagrant/php-amqp/test-amqplib.php:0
    0.1307    1942248   2. PhpAmqpLib\Channel\AMQPChannel->basic_publish() /home/vagrant/php-amqp/test-amqplib.php:32
    0.1307    1944072   3. PhpAmqpLib\Channel\AMQPChannel->pre_publish() /home/vagrant/php-amqp/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Channel/AMQPChannel.php:1092
    0.1308    1944312   4. sprintf() /home/vagrant/php-amqp/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Channel/AMQPChannel.php:1050

PHP Warning:  mb_strlen() expects parameter 1 to be string, array given in /home/vagrant/php-amqp/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Wire/AMQPWriter.php on line 331
PHP Stack trace:
PHP   1. {main}() /home/vagrant/php-amqp/test-amqplib.php:0
PHP   2. PhpAmqpLib\Channel\AMQPChannel->basic_publish() /home/vagrant/php-amqp/test-amqplib.php:32
PHP   3. PhpAmqpLib\Channel\AMQPChannel->pre_publish() /home/vagrant/php-amqp/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Channel/AMQPChannel.php:1092
PHP   4. PhpAmqpLib\Helper\Protocol\Protocol091->basicPublish() /home/vagrant/php-amqp/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Channel/AMQPChannel.php:1059
PHP   5. PhpAmqpLib\Wire\AMQPWriter->write_shortstr() /home/vagrant/php-amqp/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Helper/Protocol/Protocol091.php:622
PHP   6. mb_strlen() /home/vagrant/php-amqp/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Wire/AMQPWriter.php:331

Warning: mb_strlen() expects parameter 1 to be string, array given in /home/vagrant/php-amqp/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Wire/AMQPWriter.php on line 331

Call Stack:
    0.0007     244904   1. {main}() /home/vagrant/php-amqp/test-amqplib.php:0
    0.1307    1942248   2. PhpAmqpLib\Channel\AMQPChannel->basic_publish() /home/vagrant/php-amqp/test-amqplib.php:32
    0.1307    1944072   3. PhpAmqpLib\Channel\AMQPChannel->pre_publish() /home/vagrant/php-amqp/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Channel/AMQPChannel.php:1092
    0.1331    1944680   4. PhpAmqpLib\Helper\Protocol\Protocol091->basicPublish() /home/vagrant/php-amqp/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Channel/AMQPChannel.php:1059
    0.1332    1945896   5. PhpAmqpLib\Wire\AMQPWriter->write_shortstr() /home/vagrant/php-amqp/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Helper/Protocol/Protocol091.php:622
    0.1332    1946136   6. mb_strlen() /home/vagrant/php-amqp/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Wire/AMQPWriter.php:331

PHP Notice:  Array to string conversion in /home/vagrant/php-amqp/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Wire/AMQPWriter.php on line 337
PHP Stack trace:
PHP   1. {main}() /home/vagrant/php-amqp/test-amqplib.php:0
PHP   2. PhpAmqpLib\Channel\AMQPChannel->basic_publish() /home/vagrant/php-amqp/test-amqplib.php:32
PHP   3. PhpAmqpLib\Channel\AMQPChannel->pre_publish() /home/vagrant/php-amqp/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Channel/AMQPChannel.php:1092
PHP   4. PhpAmqpLib\Helper\Protocol\Protocol091->basicPublish() /home/vagrant/php-amqp/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Channel/AMQPChannel.php:1059
PHP   5. PhpAmqpLib\Wire\AMQPWriter->write_shortstr() /home/vagrant/php-amqp/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Helper/Protocol/Protocol091.php:622

Notice: Array to string conversion in /home/vagrant/php-amqp/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Wire/AMQPWriter.php on line 337

Call Stack:
    0.0007     244904   1. {main}() /home/vagrant/php-amqp/test-amqplib.php:0
    0.1307    1942248   2. PhpAmqpLib\Channel\AMQPChannel->basic_publish() /home/vagrant/php-amqp/test-amqplib.php:32
    0.1307    1944072   3. PhpAmqpLib\Channel\AMQPChannel->pre_publish() /home/vagrant/php-amqp/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Channel/AMQPChannel.php:1092
    0.1331    1944680   4. PhpAmqpLib\Helper\Protocol\Protocol091->basicPublish() /home/vagrant/php-amqp/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Channel/AMQPChannel.php:1059
    0.1332    1945896   5. PhpAmqpLib\Wire\AMQPWriter->write_shortstr() /home/vagrant/php-amqp/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Helper/Protocol/Protocol091.php:622

PHP Warning:  mb_strlen() expects parameter 1 to be string, array given in /home/vagrant/php-amqp/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Wire/AMQPWriter.php on line 331
PHP Stack trace:
PHP   1. {main}() /home/vagrant/php-amqp/test-amqplib.php:0
PHP   2. PhpAmqpLib\Channel\AMQPChannel->basic_get() /home/vagrant/php-amqp/test-amqplib.php:34
PHP   3. PhpAmqpLib\Helper\Protocol\Protocol091->basicGet() /home/vagrant/php-amqp/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Channel/AMQPChannel.php:987
PHP   4. PhpAmqpLib\Wire\AMQPWriter->write_shortstr() /home/vagrant/php-amqp/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Helper/Protocol/Protocol091.php:667
PHP   5. mb_strlen() /home/vagrant/php-amqp/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Wire/AMQPWriter.php:331

Warning: mb_strlen() expects parameter 1 to be string, array given in /home/vagrant/php-amqp/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Wire/AMQPWriter.php on line 331

Call Stack:
    0.0007     244904   1. {main}() /home/vagrant/php-amqp/test-amqplib.php:0
    0.1373    1945672   2. PhpAmqpLib\Channel\AMQPChannel->basic_get() /home/vagrant/php-amqp/test-amqplib.php:34
    0.1373    1945816   3. PhpAmqpLib\Helper\Protocol\Protocol091->basicGet() /home/vagrant/php-amqp/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Channel/AMQPChannel.php:987
    0.1373    1947032   4. PhpAmqpLib\Wire\AMQPWriter->write_shortstr() /home/vagrant/php-amqp/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Helper/Protocol/Protocol091.php:667
    0.1373    1947272   5. mb_strlen() /home/vagrant/php-amqp/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Wire/AMQPWriter.php:331

PHP Notice:  Array to string conversion in /home/vagrant/php-amqp/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Wire/AMQPWriter.php on line 337
PHP Stack trace:
PHP   1. {main}() /home/vagrant/php-amqp/test-amqplib.php:0
PHP   2. PhpAmqpLib\Channel\AMQPChannel->basic_get() /home/vagrant/php-amqp/test-amqplib.php:34
PHP   3. PhpAmqpLib\Helper\Protocol\Protocol091->basicGet() /home/vagrant/php-amqp/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Channel/AMQPChannel.php:987
PHP   4. PhpAmqpLib\Wire\AMQPWriter->write_shortstr() /home/vagrant/php-amqp/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Helper/Protocol/Protocol091.php:667

Notice: Array to string conversion in /home/vagrant/php-amqp/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Wire/AMQPWriter.php on line 337

Call Stack:
    0.0007     244904   1. {main}() /home/vagrant/php-amqp/test-amqplib.php:0
    0.1373    1945672   2. PhpAmqpLib\Channel\AMQPChannel->basic_get() /home/vagrant/php-amqp/test-amqplib.php:34
    0.1373    1945816   3. PhpAmqpLib\Helper\Protocol\Protocol091->basicGet() /home/vagrant/php-amqp/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Channel/AMQPChannel.php:987
    0.1373    1947032   4. PhpAmqpLib\Wire\AMQPWriter->write_shortstr() /home/vagrant/php-amqp/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Helper/Protocol/Protocol091.php:667

PHP Fatal error:  Uncaught exception 'PhpAmqpLib\Exception\AMQPProtocolConnectionException' with message 'FRAME_ERROR - cannot decode <<0,0,0,0,65,114,114,97,121,0>>' in /home/vagrant/php-amqp/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php:680
Stack trace:
#0 [internal function]: PhpAmqpLib\Connection\AbstractConnection->connection_close(Object(PhpAmqpLib\Wire\AMQPReader))
#1 /home/vagrant/php-amqp/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Channel/AbstractChannel.php(170): call_user_func(Array, Object(PhpAmqpLib\Wire\AMQPReader))
#2 /home/vagrant/php-amqp/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Channel/AbstractChannel.php(362): PhpAmqpLib\Channel\AbstractChannel->dispatch('10,50', '\x01\xF5;FRAME_ERROR ...', NULL)
#3 /home/vagrant/php-amqp/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php(583): PhpAmqpLib\Channel\AbstractChannel->wait()
#4 /home/vagrant/php-amqp/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Channel/AbstractChannel.php(190): PhpAmqpLib\Connection\AbstractConn in /home/vagrant/php-amqp/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php on line 680

Fatal error: Uncaught exception 'PhpAmqpLib\Exception\AMQPProtocolConnectionException' with message 'FRAME_ERROR - cannot decode <<0,0,0,0,65,114,114,97,121,0>>' in /home/vagrant/php-amqp/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php on line 680

PhpAmqpLib\Exception\AMQPProtocolConnectionException: FRAME_ERROR - cannot decode <<0,0,0,0,65,114,114,97,121,0>> in /home/vagrant/php-amqp/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php on line 680

Call Stack:
    0.0007     244904   1. {main}() /home/vagrant/php-amqp/test-amqplib.php:0
    0.1373    1945672   2. PhpAmqpLib\Channel\AMQPChannel->basic_get() /home/vagrant/php-amqp/test-amqplib.php:34
    0.1397    1948032   3. PhpAmqpLib\Channel\AbstractChannel->wait() /home/vagrant/php-amqp/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Channel/AMQPChannel.php:994
    0.1397    1948392   4. PhpAmqpLib\Channel\AbstractChannel->next_frame() /home/vagrant/php-amqp/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Channel/AbstractChannel.php:324
    0.1397    1948392   5. PhpAmqpLib\Connection\AbstractConnection->wait_channel() /home/vagrant/php-amqp/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Channel/AbstractChannel.php:190
    0.1399    1949984   6. PhpAmqpLib\Channel\AbstractChannel->wait() /home/vagrant/php-amqp/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php:583
    0.1399    1951912   7. PhpAmqpLib\Channel\AbstractChannel->dispatch() /home/vagrant/php-amqp/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Channel/AbstractChannel.php:362
    0.1400    1952568   8. call_user_func:{/home/vagrant/php-amqp/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Channel/AbstractChannel.php:170}() /home/vagrant/php-amqp/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Channel/AbstractChannel.php:170
    0.1400    1952840   9. PhpAmqpLib\Connection\AbstractConnection->connection_close() /home/vagrant/php-amqp/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Channel/AbstractChannel.php:170
```

composer.lock (part related to your lib, i just add your lib via `composer require videlalvaro/php-amqplib
`):

```
            "name": "videlalvaro/php-amqplib",
            "version": "v2.5.0",
            "source": {
                "type": "git",
                "url": "https://github.com/videlalvaro/php-amqplib.git",
                "reference": "7989ddce7c4aa6038483d8999b12d3b1f7c81ff9"
            },
            "dist": {
                "type": "zip",
                "url": "https://api.github.com/repos/videlalvaro/php-amqplib/zipball/7989ddce7c4aa6038483d8999b12d3b1f7c81ff9",
                "reference": "7989ddce7c4aa6038483d8999b12d3b1f7c81ff9",
                "shasum": ""
            },
```

and my environment:

```
vagrant@vagrant-ubuntu-utopic-64 (php:5.6.4 -phpbrew):~/php-amqp$ lsb_release -a
No LSB modules are available.
Distributor ID:    Ubuntu
Description:    Ubuntu 14.10
Release:    14.10
Codename:    utopic
vagrant@vagrant-ubuntu-utopic-64 (php:5.6.4 -phpbrew):~/php-amqp$ php -v
PHP 5.6.4 (cli) (built: Jan 22 2015 02:06:06) (DEBUG)
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2014 Zend Technologies
    with Xdebug v2.2.7, Copyright (c) 2002-2015, by Derick Rethans
vagrant@vagrant-ubuntu-utopic-64 (php:5.6.4 -phpbrew):~/php-amqp$ sudo rabbitmqctl status
Status of node 'rabbit@vagrant-ubuntu-utopic-64' ...
[{pid,23071},
 {running_applications,
     [{rabbitmq_management,"RabbitMQ Management Console","3.5.1"},
      {rabbitmq_web_dispatch,"RabbitMQ Web Dispatcher","3.5.1"},
      {webmachine,"webmachine","1.10.3-rmq3.5.1-gite9359c7"},
      {mochiweb,"MochiMedia Web Server","2.7.0-rmq3.5.1-git680dba8"},
      {rabbitmq_management_agent,"RabbitMQ Management Agent","3.5.1"},
      {rabbit,"RabbitMQ","3.5.1"},
      {os_mon,"CPO  CXC 138 46","2.2.15"},
      {inets,"INETS  CXC 138 49","5.10.2"},
      {amqp_client,"RabbitMQ AMQP Client","3.5.1"},
      {xmerl,"XML parser","1.3.7"},
      {mnesia,"MNESIA  CXC 138 12","4.12.1"},
      {sasl,"SASL  CXC 138 11","2.4"},
      {stdlib,"ERTS  CXC 138 10","2.1"},
      {kernel,"ERTS  CXC 138 10","3.0.1"}]},
 {os,{unix,linux}},
 {erlang_version,
     "Erlang/OTP 17 [erts-6.1] [source] [64-bit] [async-threads:30] [kernel-poll:true]\n"},
 {memory,
     [{total,41857968},
      {connection_readers,0},
      {connection_writers,0},
      {connection_channels,0},
      {connection_other,5264},
      {queue_procs,1186248},
      {queue_slave_procs,0},
      {plugins,556032},
      {other_proc,13241680},
      {mnesia,256712},
      {mgmt_db,725672},
      {msg_index,163304},
      {other_ets,1205336},
      {binary,69816},
      {code,20039855},
      {atom,703377},
      {other_system,3704672}]},
 {alarms,[]},
 {listeners,[{clustering,25672,"::"},{amqp,5672,"::"}]},
 {vm_memory_high_watermark,0.4},
 {vm_memory_limit,839496499},
 {disk_free_limit,50000000},
 {disk_free,37957558272},
 {file_descriptors,
     [{total_limit,924},{total_used,3},{sockets_limit,829},{sockets_used,1}]},
 {processes,[{limit,1048576},{used,315}]},
 {run_queue,0},
 {uptime,5470}]
```

**Comment by abreksa4** [comment]
@pinepain Were you able to resolve this issue?

**Comment by pinepain** [comment]
No. I don't use php-amqlib, original issue came up when I tried direct reply-to implementation in  php-amqplib to see whether I implement it correctly in php-amqp. Maybe, my example is bogus or at that time I didn't get a concept well, can't remember and don't have much time to delve what was that. Maybe it was already fixed in some recent version, don't know. As it was long-long time ago (wow! almost 2 year :)) and as it seems to be nobody faces the issue and as it is less likely I could yield any meaningful output on this issue I decided to closed it and keep entropy low. 

If you faces with the same issue, feels free to fill a new bug and optionally refer to this issue.

**Comment by abreksa4** [comment]
No problem, thanks!

**Comment by bdchauvette** [comment]
Apologies for the necropost, but I just encountered the same error message, and landed here from Google.

In my case, it turns out that instead of passing a `string` as the third parameter of `AMQPChannel::publish`, I was passing in the return value of `AMQPChannel::queue_declare`.

It looks like the sample code above is doing the same thing:

```
$reqest_queue = $channel->queue_declare();
// . . .
$channel->basic_publish($msg, '', $reqest_queue);
```

Should be something like:

```
$queue_name = 'foobar';
$reqest_queue = $channel->queue_declare($queue_name);
// . . .
$channel->basic_publish($msg, '', $queue_name);
```

**Comment by michaelklishin** [comment]
@bdchauvette your code looks reasonable. `queue_declare` in most clients returns the response, a `queue.declare-ok` frame.

Is there an example in this repo that we should correct or is it just the code sample in this issue?

**Comment by bdchauvette** [comment]
@michaelklishin -- Sorry for the confusion! It's just the code sample in this issue.

I just wanted to comment for anyone else that stumbles onto this issue through Google, and can't figure out what their problem might be.

https://xkcd.com/979/ and all that 😄

**Comment by michaelklishin** [comment]
@bdchauvette makes perfect sense, thank you!

**Comment by pinepain** [comment]
@bdchauvette thanks for pointing me out, `$channel->queue_declare();` returns `queue.declare-ok` response which is array, not queue generated name. This was the source of original error.

Original code should be rewritten in this way:
```
$reqest_queue = $channel->queue_declare();
$queue_name = $reqest_queue[0];
// . . .
$channel->basic_publish($msg, '', $queue_name);
```

**Comment by jaypee888** [comment]
does anyone solve this issue?
