### ISSUE TITLE
(re)Connecting to SSL/TLS queue raises fatal exception

### ISSUE THREAD

**Issue by mshallop** [php-amqplib/php-amqplib#404]
My connection to RMQ is over SSL/TLS. 

I have a daemon (Parent/controller) process that forks 1, or more, children -- in said children, I establish the TLS connection to the AMQP service end-point, and consume messages.  

This method silo's the AMQP (and other) resource(s) so that, on the death of a child, none of the other daemon brokers are affected. 

The plan is, after X requests or if the child memory-leaks out, to let the child die.  So, on SIGCLD, the custom signal handler traps the event and the parent/controller uses it to restart (fork) a replacement daemon process.

This all works great up until the point where the (newly-forked) child has to consume an event.  The child throws an exception on the next event consumed:

```
[16-May-2016 16:43:40 America/Los_Angeles] PHP Fatal error:  Uncaught exception 'ErrorException' with message 'fwrite(): SSL operation failed with code 1. OpenSSL Error messages:
error:1409F07F:SSL routines:SSL3_WRITE_PENDING:bad write retry' in /home/mshallop/code/php/aura-ds/lib/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Wire/IO/StreamIO.php:281
Stack trace:
#0 [internal function]: PhpAmqpLib\Wire\IO\StreamIO->error_handler(2, 'fwrite(): SSL o...', '/home/mshallop/...', 281, Array)
#1 /home/mshallop/code/php/aura-ds/lib/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Wire/IO/StreamIO.php(281): fwrite(Resource id #72, '??????%?<?(????...', 8192)
#2 /home/mshallop/code/php/aura-ds/lib/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php(327): PhpAmqpLib\Wire\IO\StreamIO->write('??????%?<?(????...')
#3 /home/mshallop/code/php/aura-ds/lib/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php(368): PhpAmqpLib\Connection\AbstractConnection->write('??????%?<?(????...')
#4 /home/mshallop/code/php/aura-ds/lib/vendor/php-amqplib/php-amqpli in /home/mshallop/code/php/aura-ds/lib/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Wire/IO/StreamIO.php on line 281

```

How do I re-establish my SSL queue connection and consume waiting events without throwing exceptions?  (I've tried iterations involving the basic_qos() function as well - no love there either.)

**Comment by mshallop** [comment]
Closing - unable to reproduce in a minimal stub.  Problem is on my-side in resource allocation/timing.

Thanks!
