### ISSUE TITLE
delayed messages errors

### ISSUE THREAD

**Issue by texano00** [php-amqplib/php-amqplib#412]
Hi, i'm trying to execute the **demo/delayed_message.php** script but i have these errors:
I should have all up to date. 

The server version is: **3.3.5-1.1**.
The client version is the last, i've done the composer update.
The plugin is rabbitmq_delayed_message_exchange-0.0.1-rmq3.5.x-9bf265e4.ez.

```
PHP Fatal error:  Uncaught exception 'PhpAmqpLib\Exception\AMQPProtocolConnectionException' with message 'INTERNAL_ERROR' in /home/bacciarini/connect/lib/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php:661
Stack trace:
#0 [internal function]: PhpAmqpLib\Connection\AbstractConnection->connection_close(Object(PhpAmqpLib\Wire\AMQPReader))
#1 /home/bacciarini/connect/lib/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Channel/AbstractChannel.php(199): call_user_func(Array, Object(PhpAmqpLib\Wire\AMQPReader))
#2 /home/bacciarini/connect/lib/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Channel/AbstractChannel.php(341): PhpAmqpLib\Channel\AbstractChannel->dispatch('10,50', '\x02\x1D\x0EINTERNAL_ERR...', NULL)
#3 /home/bacciarini/connect/lib/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php(586): PhpAmqpLib\Channel\AbstractChannel->wait()
#4 /home/bacciarini/connect/lib/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Channel/AbstractChannel.php(217): PhpAmqpLib\Connection\AbstractConnection->wait in /home/bacciarini/connect/lib/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php on line 661
```

**From the error log:**

```
=INFO REPORT==== 13-Jun-2016::13:25:09 ===
accepting AMQP connection <0.10843.0> ([::1]:58533 -> [::1]:5672)

=ERROR REPORT==== 13-Jun-2016::13:25:09 ===
** Generic server <0.10849.0> terminating
** Last message in was {'$gen_cast',
                           {method,
                               {'basic.publish',0,<<"delayed_exchange">>,
                                   <<>>,false,false},
                               {content,60,none,
                                   <<48,0,0,0,0,13,7,120,45,100,101,108,97,121,
                                     73,0,0,27,88,2>>,
                                   rabbit_framing_amqp_0_9_1,
                                   [<<"hello">>]},
                               flow}}
** When Server state == {ch,running,rabbit_framing_amqp_0_9_1,1,<0.10843.0>,
                            <0.10847.0>,<0.10843.0>,
                            <<"[::1]:58533 -> [::1]:5672">>,
                            {lstate,<0.10848.0>,false},
                            none,1,
                            {[],[]},
                            {user,<<"guest">>,
                                [administrator],
                                rabbit_auth_backend_internal,
                                {internal_user,<<"guest">>,
                                    <<117,31,155,21,2,92,247,218,249,90,57,131,
                                      186,168,242,91,99,124,105,182>>,
                                    [administrator]}},
                            <<"/">>,<<"delayed_queue">>,
                            {dict,0,16,16,8,80,48,
                                {[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],
                                 []},
                                {{[],[],[],[],[],[],[],[],[],[],[],[],[],[],
                                  [],[]}}},
                            {state,
                                {dict,0,16,16,8,80,48,
                                    {[],[],[],[],[],[],[],[],[],[],[],[],[],
                                     [],[],[]},
                                    {{[],[],[],[],[],[],[],[],[],[],[],[],[],
                                      [],[],[]}}},
                                erlang},
                            {dict,0,16,16,8,80,48,
                                {[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],
                                 []},
                                {{[],[],[],[],[],[],[],[],[],[],[],[],[],[],
                                  [],[]}}},
                            {dict,0,16,16,8,80,48,
                                {[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],
                                 []},
                                {{[],[],[],[],[],[],[],[],[],[],[],[],[],[],
                                  [],[]}}},
                            {set,0,16,16,8,80,48,
                                {[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],
                                 []},
                                {{[],[],[],[],[],[],[],[],[],[],[],[],[],[],
                                  [],[]}}},
                            <0.10844.0>,
                            {state,fine,5000,#Ref<0.0.0.225571>},
                            false,1,
                            {{0,nil},{0,nil}},
                            [],
                            {{0,nil},{0,nil}},
                            [{<<"authentication_failure_close">>,bool,true},
                             {<<"publisher_confirms">>,bool,true},
                             {<<"consumer_cancel_notify">>,bool,true},
                             {<<"exchange_exchange_bindings">>,bool,true},
                             {<<"basic.nack">>,bool,true},
                             {<<"connection.blocked">>,bool,true}],
                            none,0}
** Reason for termination ==
** {function_clause,
       [{rabbit_delayed_message_utils,get_msg,
            [{delivery,false,false,<0.10849.0>,
                 {basic_message,
                     {resource,<<"/">>,exchange,<<"delayed_exchange">>},
                     [<<>>],
                     {content,60,
                         {'P_basic',undefined,undefined,
                             [{<<"x-delay">>,signedint,7000}],
                             2,undefined,undefined,undefined,undefined,
                             undefined,undefined,undefined,undefined,
                             undefined,undefined},
                         <<48,0,0,0,0,13,7,120,45,100,101,108,97,121,73,0,0,27,
                           88,2>>,
                         rabbit_framing_amqp_0_9_1,
                         [<<"hello">>]},
                     <<208,57,9,118,124,154,43,254,167,74,10,92,94,4,89,179>>,
                     true},
                 undefined}],
            []},
        {lists,foldl,3,[{file,"lists.erl"},{line,1261}]},
        {rabbit_delayed_message_utils,get_delay,1,[]},
        {rabbit_exchange_type_delayed_message,delay_message,2,[]},
        {rabbit_exchange_type_delayed_message,route,2,[]},
        {rabbit_exchange,route1,3,
            [{file,"src/rabbit_exchange.erl"},{line,348}]},
        {rabbit_exchange,route,2,
            [{file,"src/rabbit_exchange.erl"},{line,341}]},
        {rabbit_channel,handle_method,3,
            [{file,"src/rabbit_channel.erl"},{line,696}]}]}

=ERROR REPORT==== 13-Jun-2016::13:25:09 ===
AMQP connection <0.10843.0> (running), channel 1 - error:
{function_clause,
    [{rabbit_delayed_message_utils,get_msg,
         [{delivery,false,false,<0.10849.0>,
              {basic_message,
                  {resource,<<"/">>,exchange,<<"delayed_exchange">>},
                  [<<>>],
                  {content,60,
                      {'P_basic',undefined,undefined,
                          [{<<"x-delay">>,signedint,7000}],
                          2,undefined,undefined,undefined,undefined,undefined,
                          undefined,undefined,undefined,undefined,undefined},
                      <<48,0,0,0,0,13,7,120,45,100,101,108,97,121,73,0,0,27,88,
                        2>>,
                      rabbit_framing_amqp_0_9_1,
                      [<<"hello">>]},
                  <<208,57,9,118,124,154,43,254,167,74,10,92,94,4,89,179>>,
                  true},
              undefined}],
         []},
     {lists,foldl,3,[{file,"lists.erl"},{line,1261}]},
     {rabbit_delayed_message_utils,get_delay,1,[]},
     {rabbit_exchange_type_delayed_message,delay_message,2,[]},
     {rabbit_exchange_type_delayed_message,route,2,[]},
     {rabbit_exchange,route1,3,[{file,"src/rabbit_exchange.erl"},{line,348}]},
     {rabbit_exchange,route,2,[{file,"src/rabbit_exchange.erl"},{line,341}]},
     {rabbit_channel,handle_method,3,
         [{file,"src/rabbit_channel.erl"},{line,696}]}]}

=WARNING REPORT==== 13-Jun-2016::13:25:09 ===
Non-AMQP exit reason '{function_clause,
                       [{rabbit_delayed_message_utils,get_msg,
                         [{delivery,false,false,<0.10849.0>,
                           {basic_message,
                            {resource,<<"/">>,exchange,<<"delayed_exchange">>},
                            [<<>>],
                            {content,60,
                             {'P_basic',undefined,undefined,
                              [{<<"x-delay">>,signedint,7000}],
                              2,undefined,undefined,undefined,undefined,
                              undefined,undefined,undefined,undefined,
                              undefined,undefined},
                             <<48,0,0,0,0,13,7,120,45,100,101,108,97,121,73,0,
                               0,27,88,2>>,
                             rabbit_framing_amqp_0_9_1,
                             [<<"hello">>]},
                            <<208,57,9,118,124,154,43,254,167,74,10,92,94,4,89,
                              179>>,
                            true},
                           undefined}],
                         []},
                        {lists,foldl,3,[{file,"lists.erl"},{line,1261}]},
                        {rabbit_delayed_message_utils,get_delay,1,[]},
                        {rabbit_exchange_type_delayed_message,delay_message,
                         2,[]},
                        {rabbit_exchange_type_delayed_message,route,2,[]},
                        {rabbit_exchange,route1,3,
                         [{file,"src/rabbit_exchange.erl"},{line,348}]},
                        {rabbit_exchange,route,2,
                         [{file,"src/rabbit_exchange.erl"},{line,341}]},
                        {rabbit_channel,handle_method,3,
                         [{file,"src/rabbit_channel.erl"},{line,696}]}]}'

=INFO REPORT==== 13-Jun-2016::13:25:09 ===
closing AMQP connection <0.10843.0> ([::1]:58533 -> [::1]:5672
```

Thanks

**Comment by michaelklishin** [comment]
What RabbitMQ and delayed message exchange plugin versions are used? What does `rabbitmq status` output?

A `function_clause` in a utility function suggests a server/plugin version incompatibility.

**Comment by texano00** [comment]
The server version is: 3.3.5-1.1.
The client version is the last, i've done the composer update.
The plugin is rabbitmq_delayed_message_exchange-0.0.1-rmq3.5.x-9bf265e4.ez.

The service rabbitmmq-server status output is:

● rabbitmq-server.service - LSB: Enable AMQP service provided by RabbitMQ broker
   Loaded: loaded (/etc/init.d/rabbitmq-server)
   Active: active (running) since Mon 2016-06-13 10:22:09 UTC; 3h 20min ago
  Process: 20258 ExecStop=/etc/init.d/rabbitmq-server stop (code=exited, status=0/SUCCESS)
  Process: 17923 ExecReload=/etc/init.d/rabbitmq-server reload (code=exited, status=0/SUCCESS)
  Process: 20354 ExecStart=/etc/init.d/rabbitmq-server start (code=exited, status=0/SUCCESS)
   CGroup: /system.slice/rabbitmq-server.service
           └─393 /usr/lib/erlang/erts-6.2/bin/epmd -daemon

Jun 13 13:42:25 informabene su[17977]: pam_unix(su:session): session opened for user rabbitmq by (uid=0)
Jun 13 13:42:28 informabene su[18025]: Successful su for rabbitmq by root
Jun 13 13:42:28 informabene su[18025]: + ??? root:rabbitmq
Jun 13 13:42:28 informabene su[18025]: pam_unix(su:session): session opened for user rabbitmq by (uid=0)
Jun 13 13:42:28 informabene su[18025]: pam_unix(su:session): session closed for user rabbitmq
Jun 13 13:42:28 informabene su[18084]: Successful su for rabbitmq by root
Jun 13 13:42:28 informabene su[18084]: + ??? root:rabbitmq
Jun 13 13:42:28 informabene su[18084]: pam_unix(su:session): session opened for user rabbitmq by (uid=0)
Jun 13 13:42:30 informabene su[18084]: pam_unix(su:session): session closed for user rabbitmq
Jun 13 13:42:30 informabene rabbitmq-server[17923]: Restarting message broker: rabbitmq-server.
Jun 13 13:42:30 informabene systemd[1]: Reloaded LSB: Enable AMQP service provided by RabbitMQ broker.

**Comment by michaelklishin** [comment]
See the section on [Supported RabbitMQ versions](https://github.com/rabbitmq/rabbitmq-delayed-message-exchange/#supported-rabbitmq-versions).

**Comment by texano00** [comment]
Thanks very much.
