### ISSUE TITLE
INTERNAL_ERROR with delayed demo

### ISSUE THREAD

**Issue by libasoles** [php-amqplib/php-amqplib#443]
I'm traying the delayed messages plugin, but I'm stucked with an error. I tried with my existing code, and also with the demo:
https://github.com/php-amqplib/php-amqplib/blob/master/demo/delayed_message.php

Error is the following:
`Fatal error: Uncaught PhpAmqpLib\Exception\AMQPProtocolConnectionException: INT
ERNAL_ERROR in C:\wamp64\www\populador\vendor\php-amqplib\php-amqplib\PhpAmqpLi
b\Connection\AbstractConnection.php:661
Stack trace:
#0 [internal function]: PhpAmqpLib\Connection\AbstractConnection->connection_cl
ose(Object(PhpAmqpLib\Wire\AMQPReader))
#1 C:\wamp64\www\populador\vendor\php-amqplib\php-amqplib\PhpAmqpLib\Channel\Ab
stractChannel.php(199): call_user_func(Array, Object(PhpAmqpLib\Wire\AMQPReader
))
#2 C:\wamp64\www\populador\vendor\php-amqplib\php-amqplib\PhpAmqpLib\Channel\Ab
stractChannel.php(341): PhpAmqpLib\Channel\AbstractChannel->dispatch('10,50', '
\x02\x1D\x0EINTERNAL_ERR...', NULL)
#3 C:\wamp64\www\populador\vendor\php-amqplib\php-amqplib\PhpAmqpLib\Connection
\AbstractConnection.php(586): PhpAmqpLib\Channel\AbstractChannel->wait()
#4 C:\wamp64\www\populador\vendor\php-amqplib\php-amqplib\PhpAmqpLib\Channel\Ab
stractChannel.php(217): PhpAmqpLib\Connection\AbstractConnection->wait_channel(
1, 0)
#5 C:\wamp64\www\populador\vendor\ph in C:\wamp64\www\populador\vendor\php-amqp
lib\php-amqplib\PhpAmqpLib\Connection\AbstractConnection.php on line 661
`

That happens when executing:
$channel->close();
$connection->close();

If I exit the script before these lines there's no error (but it doesn't work anyway)

--
My code is:
```
try{

        $metadata = [
            'delivery_mode' => 2, # make message persistent    
            //"x-delay"=> $delay  
        ];
        $message = new AMQPMessage($msg, $metadata);

        $headers = new AMQPTable(["x-delay"=> $delay]);
        $message->set('application_headers', $headers);
    
        $channel->basic_publish($message, $exchange_name/*, $routing_key*/);
        
    } catch(Exception $e){

        die($e->getmessage());
    }    
```

If I don't pass the $headers then the message is received but the consumer crashes:
`Fatal error: Uncaught OutOfBoundsException: No "application_headers" property
in C:\wamp64\www\populador\vendor\php-amqplib\php-amqplib\PhpAmqpLib\Wire\Gene
ricContent.php:78
Stack trace:
#0 C:\wamp64\www\populador\listener_populador_desa.php(41): PhpAmqpLib\Wire\Ge
nericContent->get('application_hea...')
#1 [internal function]: {closure}(Object(PhpAmqpLib\Message\AMQPMessage))
#2 C:\wamp64\www\populador\vendor\php-amqplib\php-amqplib\PhpAmqpLib\Channel\A
MQPChannel.php(983): call_user_func(Object(Closure), Object(PhpAmqpLib\Message
\AMQPMessage))
#3 [internal function]: PhpAmqpLib\Channel\AMQPChannel->basic_deliver(Object(P
hpAmqpLib\Wire\AMQPReader), Object(PhpAmqpLib\Message\AMQPMessage))
#4 C:\wamp64\www\populador\vendor\php-amqplib\php-amqplib\PhpAmqpLib\Channel\A
bstractChannel.php(202): call_user_func(Array, Object(PhpAmqpLib\Wire\AMQPRead
er), Object(PhpAmqpLib\Message\AMQPMessage))
#5 C:\wamp64\www\populador\vendor\php-amqplib\php-amqplib\PhpAmqpLib\Channel\A
bstractChannel.php(341): PhpAmqpLib\Channel\AbstractChannel->d in C:\wamp64\ww
w\populador\vendor\php-amqplib\php-amqplib\PhpAmqpLib\Wire\GenericContent.php
on line 78
`

Any clue?

**Comment by libasoles** [comment]
Tried with another machine. Message is now received and sender don't complain. But there's an error crashing the receiver anyway. See:
`Fatal error: Uncaught PhpAmqpLib\Exception\AMQPProtocolChannelException: PRECO
NDITION_FAILED - unknown delivery tag 1 in C:\wamp64\www\populador\vendor\php-
amqplib\php-amqplib\PhpAmqpLib\Channel\AMQPChannel.php:188
Stack trace:
#0 [internal function]: PhpAmqpLib\Channel\AMQPChannel->channel_close(Object(P
hpAmqpLib\Wire\AMQPReader))
#1 C:\wamp64\www\populador\vendor\php-amqplib\php-amqplib\PhpAmqpLib\Channel\A
bstractChannel.php(199): call_user_func(Array, Object(PhpAmqpLib\Wire\AMQPRead
er))
#2 C:\wamp64\www\populador\vendor\php-amqplib\php-amqplib\PhpAmqpLib\Channel\A
bstractChannel.php(341): PhpAmqpLib\Channel\AbstractChannel->dispatch('20,40',
 '\x01\x96,PRECONDITION...', NULL)
#3 C:\wamp64\www\populador\listener_populador_desa.php(51): PhpAmqpLib\Channel
\AbstractChannel->wait()
#4 {main}
  thrown in C:\wamp64\www\populador\vendor\php-amqplib\php-amqplib\PhpAmqpLib\
Channel\AMQPChannel.php on line 188`

**Comment by libasoles** [comment]
Sorry, it's a problem with versions (Erlang, Rabbit). I'm closing this ticket.
