### ISSUE TITLE
PCNTL SIGTERM break on select ?

### ISSUE THREAD

**Issue by Bupyc** [php-amqplib/php-amqplib#458]
I am use
define('AMQP_WITHOUT_SIGNALS', true);
And i am use custom sighandler with flag to exit

If i send kill 15 - 
PHP Fatal error:  Uncaught PhpAmqpLib\Exception\AMQPIOWaitException: A network error occured while awaiting for incoming data in /usr/share/nginx/html/pushall/vendor/PhpAmqpLib/Wire/AMQPReader.php:128
Stack trace:
#0 /usr/share/nginx/html/pushall/vendor/PhpAmqpLib/Wire/AMQPReader.php(148): PhpAmqpLib\Wire\AMQPReader->wait()
#1 /usr/share/nginx/html/pushall/vendor/PhpAmqpLib/Wire/AMQPReader.php(106): PhpAmqpLib\Wire\AMQPReader->rawread(7)
#2 /usr/share/nginx/html/pushall/vendor/PhpAmqpLib/Connection/AbstractConnection.php(508): PhpAmqpLib\Wire\AMQPReader->read(7)
#3 /usr/share/nginx/html/pushall/vendor/PhpAmqpLib/Connection/AbstractConnection.php(555): PhpAmqpLib\Connection\AbstractConnection->wait_frame(5)
#4 /usr/share/nginx/html/pushall/vendor/PhpAmqpLib/Channel/AbstractChannel.php(217): PhpAmqpLib\Connection\AbstractConnection->wait_channel(1, 5)
#5 /usr/share/nginx/html/pushall/vendor/PhpAmqpLib/Channel/AbstractChannel.php(328): PhpAmqpLib\Channel\AbstractChannel->next_frame(5)
#6 /usr/share/nginx/html/pushall/connect_rabb in /usr/share/nginx/html/pushall/vendor/PhpAmqpLib/Wire/AMQPReader.php on line 128

global $needDie;
        $channel = $this->getChannel($queue_name);
        $channel->basic_consume($queue_name, '', false, false, false, false, $callback);
        while(count($channel->callbacks)) {
            try {
                $channel->wait(null, false, $timeout);
            }catch (PhpAmqpLib\Exception\AMQPTimeoutException $e){
                pcntl_signal_dispatch();  //обработаем внешние сообщения
            if($needDie) {
                $this->log('WORKER die');
                $rabbit->getChannel('pushall-allpushes')->close();
                $rabbit->connection->close();
                //exit;
            }
            }
        }

**Comment by hairyhum** [comment]
The root cause of that is that `channel->wait` function behaves differently when it has a timeout and when it doesn't. With timeout the AMQPReader will wait using `select` and fail with the exception you see if the select fails (like it does during the signal). Without a timeout, `StreamIO` will try to read data from a socket and process signal interruptions (if `pcntl` is available) when reads fail.
Instead of catching `AMQPTimeoutException`, you could call `wait` without a timeout and rely on `StreamIO` to call `pcntl_signal_dispatch`
Ideally this issue should be addressed by supporting signal dispatch on select with timeout.

**Comment by acasademont** [comment]
HI @hairyhum has someone managed to fix the issue of signals + timeout? Thanks!

**Comment by Soullivaneuh** [comment]
Maybe can we just properly stop the channel waiting on signal catch?

**Comment by makasim** [comment]
[enqueue/amqp-lib](https://github.com/php-enqueue/enqueue-dev/blob/master/docs/transport/amqp_lib.md) (a wrapper above php-amqplib) solves this issue by [muting the exception if there was a signal](https://github.com/php-enqueue/enqueue-dev/blob/master/pkg/amqp-lib/AmqpContext.php#L387)

**Comment by SunMar** [comment]
Hi, this is a problem for me as well.

I think what @Soullivaneuh says is the in right direction, but php-amqplib doesn't have to handle this. What it needs is a method to allow the wait to be interrupted. Thanks to asynchronous signal handling (#468) this can be managed by the developer implementing the package. If they want signal handling they can just create one and then should be able to call something like `$channel->stop_wait()` to gracefully stop php-amqplib from waiting. Then when `stream_select()` raises an error but the `wait()` was stopped, the error can just be ignored and whatever logic is in place to check if the wait was stopped should take care of the rest. The `stop_wait()` should work regardless of whether a timeout is used.

Right now the only way to deal with signals is to always specify a timeout, because then when a signal arrives the `stream_select()` is interrupted and with that the `wait()`. Then you can catch the `AMQPIOWaitException` (available since 2.8.2, which unfortunately is still in RC status) and go on with your graceful termination. If you don't specify a timeout then either signals are not processed because blocking streams are used (`AMQP_WITHOUT_SIGNALS` is defined) or non-blocking streams are used but you have no way to end the `wait()`, it just keeps going. Termination becomes impossible.

php-amqplib should not be registering any signal handlers by itself because as soon as you register a signal handler you change the execution behaviour (i.e. the script isn't terminated immediately anymore upon a SIGTERM/SIGINT but handling the signal is turned over to the registered signal handlers), and that I think is not something a library should do (unless explicitly activated as such by the developer implementing the library).

**Comment by lukebakken** [comment]
Please test the upcoming `2.9.0-rc1` release. @SunMar we may change how signals are used in version `3.0.0` of this library. If you could submit a pull request implementing your suggestions we would appreciate it.

**Comment by SunMar** [comment]
@lukebakken what was changed in `2.9.0-rc1` that is relevant for this? also what do you plan to change for `3.0.0`? I can try to make a PR, what branch should I do that in then? Just against master, and should I wait for some more changes before doing it? I wouldn't want to do it now and then have to re-do it in a few weeks because various things were refactored for version 3.

**Comment by lukebakken** [comment]
> what was changed in `2.9.0-rc1` that is relevant for this?

I can't point to a specific change, but there have been several around the interaction between signals and `select`. Since this issue (#458) doesn't contain a complete, runnable code sample I can use to test the reported issue ([this is not sufficient](https://github.com/php-amqplib/php-amqplib/issues/458#issue-200231036)) I have to rely on other people to test.

> php-amqplib should not be registering any signal handlers by itself

This is the change I would like to see a PR for. It would not be backwards compatible (right?) so it would have to go into version `3.0.0`. I suggest basing it on `master` and I / we can rebase it as necessary if further `2.9.X` releases happen. Thanks.

**Comment by SunMar** [comment]
> This is the change I would like to see a PR for. It would not be backwards compatible (right?) so it would have to go into version `3.0.0`. I suggest basing it on `master` and I / we can rebase it as necessary if further `2.9.X` releases happen. Thanks.

php-amqplib currently does not register any signal handlers. It calls `pcntl_signal_dispatch()` to dispatch them if any are registered, but it doesn't use `pcntl_signal()` itself to register any. My suggestion is to keep it that way, as I don't believe registering signal handlers should be the responsibility of a library since it changes the default behaviour of PHP when a signal arrives. Implementing signal handlers should I think always be done in the root project (i.e. by the developer implementing the library, not the library itself).

My suggestion is only to add a `$channel->stop_wait()` function, since it's a new function it should be backwards compatible. It would just gracefully end a `wait()`, and if you don't call the function the behaviour should remain the same as it is now.

What happens with the `stop_wait()` is then up to whoever is using php-amqplib, but it will allow anyone to write a signal handler that gracefully stops the `wait()` so the process can be terminated.

**Comment by lukebakken** [comment]
I am moving this out of the `3.0.0` release. It has been open for four years so it must not affect too many users.
