### ISSUE TITLE
Broken pipe or closed connection.

### ISSUE THREAD

**Issue by kamranahmedse** [php-amqplib/php-amqplib#478]
I am not able to get the demos to work.

Here is the crash dump
```
 =CRASH REPORT==== 18-Apr-2017::09:14:28 ===
   crasher:
     initial call: rabbit_channel:init/1
     pid: <0.598.0>
     registered_name: []
     exception exit: {amqp_error,internal_error,
                                 "Interceptor: more than one module handles {set,1,16,16,8,80,48,\n                                           {[],[],[],[],[],[],[],[],[],[],[],\n                                            [],[],[],[],[]},\n                                           {{[],[],[],[],[],[],[],[],\n                                             ['basic.publish'],\n                                             [],[],[],[],[],[],[]}}}\n",
                                 none}
       in function  gen_server2:init_it/6 (src/gen_server2.erl, line 597)
     ancestors: [<0.595.0>,<0.594.0>,<0.591.0>,<0.590.0>,<0.290.0>,<0.289.0>,
                   <0.288.0>,rabbit_sup,<0.191.0>]
     messages: []
     links: [<0.595.0>]
     dictionary: [{process_name,
                       {rabbit_channel,
                           {<<"172.18.0.6:50446 -> 172.18.0.5:5772">>,1}}}]
     trap_exit: true
     status: running
     heap_size: 1598
     stack_size: 27
     reductions: 2143
   neighbours:

 =CRASH REPORT==== 18-Apr-2017::09:14:28 ===
   crasher:
     initial call: rabbit_reader:init/4
     pid: <0.592.0>
     registered_name: []
     exception error: no match of right hand side value
                      {error,
                       {'EXIT',
                        {{badmatch,
                          {error,
                           {{amqp_error,internal_error,
                             "Interceptor: more than one module handles {set,1,16,16,8,80,48,\n                                           {[],[],[],[],[],[],[],[],[],[],[],\n                                            [],[],[],[],[]},\n                                           {{[],[],[],[],[],[],[],[],\n                                             ['basic.publish'],\n                                             [],[],[],[],[],[],[]}}}\n",
                             none},
                            {child,undefined,channel,
                             {rabbit_channel,start_link,
                              [1,<0.592.0>,<0.596.0>,<0.592.0>,
                               <<"172.18.0.6:50446 -> 172.18.0.5:5772">>,
                               rabbit_framing_amqp_0_9_1,
                               {user,<<"it-admin">>,
                                [administrator],
                                [{rabbit_auth_backend_internal,none}]},
                               <<"/">>,
                               [{<<"authentication_failure_close">>,bool,true},
                                {<<"publisher_confirms">>,bool,true},
                                {<<"consumer_cancel_notify">>,bool,true},
                                {<<"exchange_exchange_bindings">>,bool,true},
                                {<<"basic.nack">>,bool,true},
                                {<<"connection.blocked">>,bool,true}],
                               <0.593.0>,<0.597.0>]},
                             intrinsic,70000,worker,
                             [rabbit_channel]}}}},
                         [{rabbit_channel_sup,start_link,1,
                           [{file,"src/rabbit_channel_sup.erl"},{line,63}]},
                          {supervisor2,do_start_child_i,3,
                           [{file,"src/supervisor2.erl"},{line,392}]},
                          {supervisor2,handle_call,3,
                           [{file,"src/supervisor2.erl"},{line,418}]},
                          {gen_server,try_handle_call,4,
                           [{file,"gen_server.erl"},{line,615}]},
                          {gen_server,handle_msg,5,
                           [{file,"gen_server.erl"},{line,647}]},
                          {proc_lib,init_p_do_apply,3,
                           [{file,"proc_lib.erl"},{line,247}]}]}}}
       in function  rabbit_reader:create_channel/2 (src/rabbit_reader.erl, line 924)
       in call from rabbit_reader:process_frame/3 (src/rabbit_reader.erl, line 980)
       in call from rabbit_reader:handle_input/3 (src/rabbit_reader.erl, line 1043)
       in call from rabbit_reader:recvloop/4 (src/rabbit_reader.erl, line 451)
       in call from rabbit_reader:run/1 (src/rabbit_reader.erl, line 433)
       in call from rabbit_reader:start_connection/4 (src/rabbit_reader.erl, line 390)
     ancestors: [<0.590.0>,<0.290.0>,<0.289.0>,<0.288.0>,rabbit_sup,
                   <0.191.0>]
     messages: [{'EXIT',#Port<0.24209>,normal}]
     links: [<0.590.0>]
     dictionary: [{process_name,
                       {rabbit_reader,
                           <<"172.18.0.6:50446 -> 172.18.0.5:5772">>}}]
     trap_exit: true
     status: running
     heap_size: 4185
     stack_size: 27
     reductions: 3889
   neighbours:

 =SUPERVISOR REPORT==== 18-Apr-2017::09:14:28 ===
      Supervisor: {<0.590.0>,rabbit_connection_sup}
      Context:    child_terminated
      Reason:     {badmatch,
                   {error,
                    {'EXIT',
                     {{badmatch,
                       {error,
                        {{amqp_error,internal_error,
                          "Interceptor: more than one module handles {set,1,16,16,8,80,48,\n                                           {[],[],[],[],[],[],[],[],[],[],[],\n                                            [],[],[],[],[]},\n                                           {{[],[],[],[],[],[],[],[],\n                                             ['basic.publish'],\n                                             [],[],[],[],[],[],[]}}}\n",
                          none},
                         {child,undefined,channel,
                          {rabbit_channel,start_link,
                           [1,<0.592.0>,<0.596.0>,<0.592.0>,
                            <<"172.18.0.6:50446 -> 172.18.0.5:5772">>,
                            rabbit_framing_amqp_0_9_1,
                            {user,<<"it-admin">>,
                             [administrator],
                             [{rabbit_auth_backend_internal,none}]},
                            <<"/">>,
                            [{<<"authentication_failure_close">>,bool,true},
                             {<<"publisher_confirms">>,bool,true},
                             {<<"consumer_cancel_notify">>,bool,true},
                             {<<"exchange_exchange_bindings">>,bool,true},
                             {<<"basic.nack">>,bool,true},
                             {<<"connection.blocked">>,bool,true}],
                            <0.593.0>,<0.597.0>]},
                          intrinsic,70000,worker,
                          [rabbit_channel]}}}},
                      [{rabbit_channel_sup,start_link,1,
                        [{file,"src/rabbit_channel_sup.erl"},{line,63}]},
                       {supervisor2,do_start_child_i,3,
                        [{file,"src/supervisor2.erl"},{line,392}]},
                       {supervisor2,handle_call,3,
                        [{file,"src/supervisor2.erl"},{line,418}]},
                       {gen_server,try_handle_call,4,
                        [{file,"gen_server.erl"},{line,615}]},
                       {gen_server,handle_msg,5,
                        [{file,"gen_server.erl"},{line,647}]},
                       {proc_lib,init_p_do_apply,3,
                        [{file,"proc_lib.erl"},{line,247}]}]}}}}
      Offender:   [{pid,<0.592.0>},
                   {name,reader},
                   {mfargs,
                       {rabbit_reader,start_link,
                           [<0.591.0>,
                            {acceptor,{0,0,0,0,0,0,0,0},5772},
                            #Port<0.24209>]}},
                   {restart_type,intrinsic},
                   {shutdown,30000},
                   {child_type,worker}]

```
And debug output looks like
```
< [hex]:
0000  41 4D 51 50 00 00 09 01                            AMQP....

waiting for 10,10
waiting for a new frame
> 10,10: Connection.start
Start from server, version: 0.9, properties: capabilities=(publisher_confirms=1, exchange_exchange_bindings=1, basic.nack=1, consumer_cancel_notify=1, connection.blocked=1, consumer_priorities=1, authentication_failure_close=1, per_consumer_qos=1, direct_reply_to=1), cluster_name=rabbit@116d421c2ff6, copyright=Copyright (C) 2007-2016 Pivotal Software, Inc., information=Licensed under the MPL.  See http://www.rabbitmq.com/, platform=Erlang/OTP, product=RabbitMQ, version=3.6.9, mechanisms: AMQPLAIN, PLAIN, locales: en_US
< 10,11:: Connection.start_ok
< [hex]:
0000  01 00 00 00 00 01 35 00  0A 00 0B 00 00 00 F3 07   ......5. ......�.
0010  70 72 6F 64 75 63 74 53  00 00 00 07 41 4D 51 50   productS ....AMQP
0020  4C 69 62 08 70 6C 61 74  66 6F 72 6D 53 00 00 00   Lib.plat formS...
0030  03 50 48 50 07 76 65 72  73 69 6F 6E 53 00 00 00   .PHP.ver sionS...
0040  03 32 2E 36 0B 69 6E 66  6F 72 6D 61 74 69 6F 6E   .2.6.inf ormation
0050  53 00 00 00 00 09 63 6F  70 79 72 69 67 68 74 53   S.....co pyrightS
0060  00 00 00 00 0C 63 61 70  61 62 69 6C 69 74 69 65   .....cap abilitie
0070  73 46 00 00 00 8C 1C 61  75 74 68 65 6E 74 69 63   sF...�.a uthentic
0080  61 74 69 6F 6E 5F 66 61  69 6C 75 72 65 5F 63 6C   ation_fa ilure_cl
0090  6F 73 65 74 01 12 70 75  62 6C 69 73 68 65 72 5F   oset..pu blisher_
00A0  63 6F 6E 66 69 72 6D 73  74 01 16 63 6F 6E 73 75   confirms t..consu
00B0  6D 65 72 5F 63 61 6E 63  65 6C 5F 6E 6F 74 69 66   mer_canc el_notif
00C0  79 74 01 1A 65 78 63 68  61 6E 67 65 5F 65 78 63   yt..exch ange_exc
00D0  68 61 6E 67 65 5F 62 69  6E 64 69 6E 67 73 74 01   hange_bi ndingst.
00E0  0A 62 61 73 69 63 2E 6E  61 63 6B 74 01 12 63 6F   .basic.n ackt..co
00F0  6E 6E 65 63 74 69 6F 6E  2E 62 6C 6F 63 6B 65 64   nnection .blocked
0100  74 01 08 41 4D 51 50 4C  41 49 4E 00 00 00 27 05   t..AMQPL AIN...'.
0110  4C 4F 47 49 4E 53 00 00  00 08 69 74 2D 61 64 6D   LOGINS.. ..it-adm
0120  69 6E 08 50 41 53 53 57  4F 52 44 53 00 00 00 06   in.PASSW ORDS....
0130  31 32 33 34 35 36 05 65  6E 5F 55 53 CE            123456.e n_US�

< 10,11:: Connection.start_ok
waiting for 10,20, 10,30
waiting for a new frame
> 10,30: Connection.tune
< 10,31:: Connection.tune_ok
< [hex]:
0000  01 00 00 00 00 00 0C 00  0A 00 1F FF FF 00 02 00   ........ ...��...
0010  00 00 00 CE                                        ...�

< 10,31:: Connection.tune_ok
< 10,40:: Connection.open
< [hex]:
0000  01 00 00 00 00 00 08 00  0A 00 28 01 2F 00 00 CE   ........ ..(./..�

< 10,40:: Connection.open
waiting for 10,41
waiting for a new frame
> 10,41: Connection.open_ok
Open OK! known_hosts:
using channel_id: 1
< 20,10:: Channel.open
< [hex]:
0000  01 00 01 00 00 00 05 00  14 00 0A 00 CE            ........ ....�

< 20,10:: Channel.open
waiting for 20,11
waiting for a new frame
PHP Fatal error:  Uncaught PhpAmqpLib\Exception\AMQPRuntimeException: Broken pipe or closed connection in /var/www/rabbit/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Wire/IO/StreamIO.php:207
Stack trace:
#0 /var/www/rabbit/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Wire/AMQPReader.php(149): PhpAmqpLib\Wire\IO\StreamIO->read(7)
#1 /var/www/rabbit/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Wire/AMQPReader.php(106): PhpAmqpLib\Wire\AMQPReader->rawread(7)
#2 /var/www/rabbit/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php(508): PhpAmqpLib\Wire\AMQPReader->read(7)
#3 /var/www/rabbit/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php(555): PhpAmqpLib\Connection\AbstractConnection->wait_frame(0)
#4 /var/www/rabbit/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Channel/AbstractChannel.php(217): PhpAmqpLib\Connection\AbstractConnection->wait_channel(1, 0)
#5 /var/www/rabbit/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Channel/AbstractChannel.php(328): PhpAmqpLib\Channel\AbstractChannel->next_fram in /var/www/rabbit/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Wire/IO/StreamIO.php on line 207
```

I verified the credentials and permissions to the VHOST, everything seems to be fine.

**Comment by michaelklishin** [comment]
You have two plugins that use channel interceptors (e.g. rabbitmq-message-timestamp and rabbitmq-routing-node-stamp). This is currently not supported by RabbitMQ. Choose one or the other.

**Comment by michaelklishin** [comment]
…or disable both plugins as they are not necessary for running tutorials (and most systems, in fact).

**Comment by kamranahmedse** [comment]
Aah, working now. Thanks :)

**Comment by michaelklishin** [comment]
I added a note to the READMEs of both plugins.

**Comment by kamranahmedse** [comment]
Got it, thanks.

**Comment by lawrence615** [comment]
Hello @kamranahmedse ,

How did you get this to work?

**Comment by kamranahmedse** [comment]
@SunnnyGohil it could be any two; in my case, it was `rabbitmq-message-timestamp` and `rabbitmq-routing-node-stamp`
