### ISSUE TITLE
fwrite failure / not sure how to debug further

### ISSUE THREAD

**Issue by alcohol** [php-amqplib/php-amqplib#544]
We frequently see consumers crash with the following error (limited stack trace included):

```
13:10:00 ERROR     [app] ErrorException: fwrite(): send of 3124 bytes failed with errno=104 Connection reset by peer in /var/www/releases/20180214.134207-b51fad942752b1e56b132a8e81cbd281f8bfa0a6/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Wire/IO/StreamIO.php:285
Stack trace:
#0 [internal function]: PhpAmqpLib\Wire\IO\StreamIO->error_handler(8, 'fwrite(): send ...', '/var/www/releas...', 285, Array)
#1 /var/www/releases/20180214.134207-b51fad942752b1e56b132a8e81cbd281f8bfa0a6/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Wire/IO/StreamIO.php(285): fwrite(Resource id #1209, '\x01\x00\x02\x00\x00\x00#\x00<\x00(\x00\x00\x1Af...', 8192)
#2 /var/www/releases/20180214.134207-b51fad942752b1e56b132a8e81cbd281f8bfa0a6/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php(332): PhpAmqpLib\Wire\IO\StreamIO->write('\x01\x00\x02\x00\x00\x00#\x00<\x00(\x00\x00\x1Af...')
#3 /var/www/releases/20180214.134207-b51fad942752b1e56b132a8e81cbd281f8bfa0a6/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php(373): PhpAmqpLib\Connection\AbstractConnection->write('\x01\x00\x02\x00\x00\x00#\x00<\x00(\x00\x00\x1Af...')
#4 /var/www/releases/20180214.134207-b51fad942752b1e56b132a8e81cbd281f8bfa0a6/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Channel/AMQPChannel.php(1114): PhpAmqpLib\Connection\AbstractConnection->send_content(2, 60, 0, 3039, '\x90\x00\ntext/plain\x02', '{"old_flight":{...', Object(PhpAmqpLib\Wire\AMQPWriter))
#5 /var/www/releases/20180214.134207-b51fad942752b1e56b132a8e81cbd281f8bfa0a6/vendor/php-amqplib/rabbitmq-bundle/RabbitMq/Producer.php(56): PhpAmqpLib\Channel\AMQPChannel->basic_publish(Object(PhpAmqpLib\Message\AMQPMessage), 'flightinfo.upda...', '')
```

Do you have any suggestions or feedback on how we might debug this further, in order to find the root cause?

**Comment by lukebakken** [comment]
> Connection reset by peer

* Network issue?
* What is in your broker logs?
* Are you using a proxy or firewalls?

If you are using RabbitMQ, posting this question to the [mailing list](https://groups.google.com/forum/#!forum/rabbitmq-users) will ensure it reaches a larger audience.

**Comment by alcohol** [comment]
On one of the cluster machine logs I found basically a wall of the same text;

```
=INFO REPORT==== 14-Feb-2018::14:38:27 ===
accepting AMQP connection <0.32482.445> (172.20.216.6:36280 -> 172.20.216.12:5672)

=INFO REPORT==== 14-Feb-2018::14:38:27 ===
connection <0.32482.445> (172.20.216.6:36280 -> 172.20.216.12:5672): user 'streaming_api' authenticated and granted access to vhost '/'

=INFO REPORT==== 14-Feb-2018::14:38:28 ===
closing AMQP connection <0.32482.445> (172.20.216.6:36280 -> 172.20.216.12:5672, vhost: '/', user: 'streaming_api')

=INFO REPORT==== 14-Feb-2018::14:38:28 ===
accepting AMQP connection <0.32692.445> (172.20.216.7:59788 -> 172.20.216.12:5672)

=INFO REPORT==== 14-Feb-2018::14:38:28 ===
connection <0.32692.445> (172.20.216.7:59788 -> 172.20.216.12:5672): user 'streaming_api' authenticated and granted access to vhost '/'

=INFO REPORT==== 14-Feb-2018::14:38:28 ===
accepting AMQP connection <0.32547.445> (172.20.216.5:46442 -> 172.20.216.12:5672)

=INFO REPORT==== 14-Feb-2018::14:38:28 ===
connection <0.32547.445> (172.20.216.5:46442 -> 172.20.216.12:5672): user 'streaming_api' authenticated and granted access to vhost '/'

=INFO REPORT==== 14-Feb-2018::14:38:28 ===
closing AMQP connection <0.32547.445> (172.20.216.5:46442 -> 172.20.216.12:5672, vhost: '/', user: 'streaming_api')

=INFO REPORT==== 14-Feb-2018::14:38:29 ===
accepting AMQP connection <0.32763.445> (172.20.216.6:36296 -> 172.20.216.12:5672)

=INFO REPORT==== 14-Feb-2018::14:38:29 ===
connection <0.32763.445> (172.20.216.6:36296 -> 172.20.216.12:5672): user 'streaming_api' authenticated and granted access to vhost '/'

=INFO REPORT==== 14-Feb-2018::14:38:29 ===
closing AMQP connection <0.32763.445> (172.20.216.6:36296 -> 172.20.216.12:5672, vhost: '/', user: 'streaming_api')

=INFO REPORT==== 14-Feb-2018::14:38:30 ===
closing AMQP connection <0.32692.445> (172.20.216.7:59788 -> 172.20.216.12:5672, vhost: '/', user: 'streaming_api')

=INFO REPORT==== 14-Feb-2018::14:38:31 ===
accepting AMQP connection <0.32572.445> (172.20.216.9:54074 -> 172.20.216.12:5672)

=INFO REPORT==== 14-Feb-2018::14:38:31 ===
connection <0.32572.445> (172.20.216.9:54074 -> 172.20.216.12:5672): user 'streaming_api' authenticated and granted access to vhost '/'

=INFO REPORT==== 14-Feb-2018::14:38:31 ===
closing AMQP connection <0.32572.445> (172.20.216.9:54074 -> 172.20.216.12:5672, vhost: '/', user: 'streaming_api')

=INFO REPORT==== 14-Feb-2018::14:38:33 ===
accepting AMQP connection <0.32679.445> (172.20.216.8:58830 -> 172.20.216.12:5672)

=INFO REPORT==== 14-Feb-2018::14:38:33 ===
connection <0.32679.445> (172.20.216.8:58830 -> 172.20.216.12:5672): user 'streaming_api' authenticated and granted access to vhost '/'

=INFO REPORT==== 14-Feb-2018::14:38:33 ===
closing AMQP connection <0.32679.445> (172.20.216.8:58830 -> 172.20.216.12:5672, vhost: '/', user: 'streaming_api')

=INFO REPORT==== 14-Feb-2018::14:38:33 ===
accepting AMQP connection <0.32498.445> (172.20.216.11:47406 -> 172.20.216.12:5672)

=INFO REPORT==== 14-Feb-2018::14:38:33 ===
connection <0.32498.445> (172.20.216.11:47406 -> 172.20.216.12:5672): user 'streaming_api' authenticated and granted access to vhost '/'

=INFO REPORT==== 14-Feb-2018::14:38:33 ===
closing AMQP connection <0.32498.445> (172.20.216.11:47406 -> 172.20.216.12:5672, vhost: '/', user: 'streaming_api')

=INFO REPORT==== 14-Feb-2018::14:38:37 ===
accepting AMQP connection <0.32615.445> (172.20.216.6:36410 -> 172.20.216.12:5672)

=INFO REPORT==== 14-Feb-2018::14:38:37 ===
connection <0.32615.445> (172.20.216.6:36410 -> 172.20.216.12:5672): user 'streaming_api' authenticated and granted access to vhost '/'

=INFO REPORT==== 14-Feb-2018::14:38:37 ===
closing AMQP connection <0.32615.445> (172.20.216.6:36410 -> 172.20.216.12:5672, vhost: '/', user: 'streaming_api')
```

Does this mean that keep-alive is not working? It keeps reconnecting rather than keeping the connection open?

**Comment by lukebakken** [comment]
Based on your [first comment](https://github.com/php-amqplib/php-amqplib/issues/544#issue-297092065), it appears that you are using `php-amqplib` within a PHP web application. If so, you will see a new connection established to RabbitMQ per-HTTP request cycle, as PHP has no concept of long-running socket connections.

**Comment by alcohol** [comment]
No these are consumers running in a console command that is managed by supervisord. So (in theory) they should be long running processes.

**Comment by alcohol** [comment]
Never mind, I just realized these could be connections from producers, which indeed are short lived requests/processes. Back to the drawing board :-/

**Comment by liron-li** [comment]
@alcohol  , hi !  I have the same issue.   Have you solved the problem now?
