### ISSUE TITLE
Invalid frame type 65

### ISSUE THREAD

**Issue by serieznyi** [php-amqplib/php-amqplib#572]
I've already seen the issue https://github.com/php-amqplib/php-amqplib/issues/437 and it didn`t help me

We use `php-amqplib/php-amqplib:2.7.2` and RabbitMQ server in docker `rabbitmq:3.7.5-management` 

I've hide all critical data like `ip`, `port`, `user` and `password`

Creating connection example

![screenshot from 2018-06-15 13-18-00](https://user-images.githubusercontent.com/2323142/41463286-97f54908-709e-11e8-884d-e1f7fb1e97a4.png)

Server log
```
Jun 15 13:07:04 rabbitmq_server_118 docker/rabbitmq/rabbitmq[11641]: 2018-06-15 10:07:04.885 [info] <0.25661.1> accepting AMQP connection <0.25661.1> (192.168.11.53:53814 -> 172.18.0.2:5672)
Jun 15 13:07:07 rabbitmq_server_118 docker/rabbitmq/rabbitmq[11641]: 2018-06-15 10:07:07.401 [info] <0.25664.1> accepting AMQP connection <0.25664.1> (192.168.11.53:53816 -> 172.18.0.2:5672)
Jun 15 13:07:07 rabbitmq_server_118 docker/rabbitmq/rabbitmq[11641]: 2018-06-15 10:07:07.401 [warning] <0.25664.1> closing AMQP connection <0.25664.1> (192.168.11.53:53816 -> 172.18.0.2:5672):
Jun 15 13:07:07 rabbitmq_server_118 docker/rabbitmq/rabbitmq[11641]: {bad_header,<<8,0,0,0,0,0,0,206>>}
Jun 15 13:07:07 rabbitmq_server_118 docker/rabbitmq/rabbitmq[11641]: 2018-06-15 10:07:07.891 [warning] <0.25661.1> closing AMQP connection <0.25661.1> (192.168.11.53:53814 -> 172.18.0.2:5672):
Jun 15 13:07:07 rabbitmq_server_118 docker/rabbitmq/rabbitmq[11641]: {handshake_error,starting,0,{amqp_error,syntax_error,"response <<5,76,79,71,73,78,83,0,0,0,11,97,112,112,95,100,111,111,103,108,121,\n           115,8,80,65,83,83,87,79,82,68,83,0,0,0,21,101,54,97,48,101,48,51,54,\n           50,53,57,53,101,99,101,97,102,54,54,54,101>> invalid",'connection.start_ok'}}

```

Error
```
Exception 'PhpAmqpLib\Exception\AMQPRuntimeException' with message 'Invalid frame type 65'

in /var/www/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php:528

Stack trace:
#0 /var/www/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php(570): PhpAmqpLib\Connection\AbstractConnection->wait_frame(0)
#1 /var/www/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Channel/AbstractChannel.php(225): PhpAmqpLib\Connection\AbstractConnection->wait_channel(0, 0)
#2 /var/www/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Channel/AbstractChannel.php(335): PhpAmqpLib\Channel\AbstractChannel->next_frame(0)
#3 /var/www/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php(221): PhpAmqpLib\Channel\AbstractChannel->wait(Array)
#4 /var/www/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php(189): PhpAmqpLib\Connection\AbstractConnection->connect()
#5 /var/www/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Connection/AMQPStreamConnection.php(60): PhpAmqpLib\Connection\AbstractConnection->__construct('my_user', 'my_password', '/app', NULL, 'PLAIN', NULL, 'ru-RU', Object(PhpAmqpLib\Wire\IO\StreamIO), 1, 3)
#6 /var/www/config/container.command-bus.main.php(139): PhpAmqpLib\Connection\AMQPStreamConnection->__construct('my_ip', '5672', 'my_user', 'my_password', '/app', NULL, 'PLAIN', NULL, 'ru-RU', 3, 3, NULL, NULL, 1)
```

Also I tried to work with RabbitMQ using python and it works perfectly

```python
import pika

connection = pika.BlockingConnection(pika.ConnectionParameters(
               host='my_ip',
               port=5672,
               virtual_host='/app',
               credentials=pika.PlainCredentials('my_user', 'my_password')
))
channel = connection.channel()
channel.queue_declare(queue='hello')
channel.basic_publish(exchange='',
                      routing_key='hello',
                      body='Hello World!')
```

**Comment by serieznyi** [comment]
I try [demo](https://github.com/php-amqplib/php-amqplib/blob/master/demo/amqp_publisher.php) from this repo and understand what I set wrong login method in constructor.
So this is my error. 
Close issue
