### ISSUE TITLE
Signals not being handled correctly

### ISSUE THREAD

**Issue by lukebakken** [php-amqplib/php-amqplib#649]
@ramunasd - The changes in #642 introduce a new exception `AMQPIOWaitException` that is raised when certain signals are sent to a running process.

To reproduce:

* Use the latest `master` code from this project
* Run `php ./demo/amqp_consumer_signals.php`
* In another shell, run `kill -HUP "$(pgrep php)"`
* Script exits with the following instead of reconnecting:

```
PHP Fatal error:  Uncaught PhpAmqpLib\Exception\AMQPIOWaitException: A network error occurred while awaiting for incoming data in /home/lbakken/development/php-amqplib/php-amqplib/PhpAmqpLib/Wire/AMQPReader.php:137
Stack trace:
#0 /home/lbakken/development/php-amqplib/php-amqplib/PhpAmqpLib/Wire/AMQPReader.php(163): PhpAmqpLib\Wire\AMQPReader->wait()
#1 /home/lbakken/development/php-amqplib/php-amqplib/PhpAmqpLib/Wire/AMQPReader.php(107): PhpAmqpLib\Wire\AMQPReader->rawread(7)
#2 /home/lbakken/development/php-amqplib/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php(542): PhpAmqpLib\Wire\AMQPReader->read(7)
#3 /home/lbakken/development/php-amqplib/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php(593): PhpAmqpLib\Connection\AbstractConnection->wait_frame(0)
#4 /home/lbakken/development/php-amqplib/php-amqplib/PhpAmqpLib/Channel/AbstractChannel.php(228): PhpAmqpLib\Connection\AbstractConnection->wait_channel(1, 0)
#5 /home/lbakken/development/php-amqplib/php-amqplib/PhpAmqpLib/Channel/AbstractChannel.php(346): Php in /home/lbakken/development/php-amqplib/php-amqplib/PhpAmqpLib/Wire/AMQPReader.php on line 137
```

Discovered when testing #489

**Comment by ramunasd** [comment]
@lukebakken checking
