### ISSUE TITLE
getting AMQPTimeoutException on 150+ publishes/second.

### ISSUE THREAD

**Issue by Pionell** [php-amqplib/php-amqplib#665]
```
HP Fatal error:  Uncaught PhpAmqpLib\\Exception\\AMQPTimeoutException: The connection timed out after 3 sec while awaiting incoming data in /var/www/html/rabbit/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Wire/AMQPReader.php:132\nStack trace:\n#0 /var/www/html/rabbit/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Wire/AMQPReader.php(149): PhpAmqpLib\\Wire\\AMQPReader->wait()\n#1 /var/www/html/rabbit/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Wire/AMQPReader.php(106): PhpAmqpLib\\Wire\\AMQPReader-
```

my publisher code:
```

header("Cache-Control: no-cache, must-revalidate");
error_reporting(E_ALL);
require_once __DIR__ . '/vendor/autoload.php';
use PhpAmqpLib\Connection\AMQPStreamConnection;
use PhpAmqpLib\Message\AMQPMessage;


/* example get request, i make around 10 of these */
  if(isset($_GET['example']))          $example = 
  strtolower($_GET['example']); else $example = false;
/* example get request, i make around 10 of these */

//cleaning for gets
...
//cleaning for gets

  $array = array(
    "example" =>         $example,
    ...
  );


  $rabbit_queue_name = 'queue.something';
  $connection = new AMQPStreamConnection('xxx.xxx.xxx.xx', 5672, 'xxxx', 'xxxxxx');
  $channel = $connection->channel();  
  $channel->queue_declare($rabbit_queue_name, false, true, false, false);

  $msg = new AMQPMessage(
    json_encode($array,true),
    array('delivery_mode' => AMQPMessage::DELIVERY_MODE_PERSISTENT)
  );

  $channel->basic_publish($msg, '', $rabbit_queue_name);
  $channel->close();
  $connection->close();

  header('Content-Type: application/xml; charset=utf-8');
  echo '<?xml version="1.0" encoding="utf-8"?>
            <data>
              <result>1</result>
              <value>1</value>
              <msg>OK</msg>
                </data>
        <!-- END OF XML -->';
```

**Comment by lukebakken** [comment]
At the very least please provide the versions of the software you're using, including AMQP broker.

**Comment by ramunasd** [comment]
@Pionell can You submit full stack trace? First 2 lines won't help us to determine reason why timeout occurred.

**Comment by Pionell** [comment]
hey, sorry for the short description. RabbitMQ 3.6.10, Erlang 20.2.2, php 7.2

```
Fatal error: Uncaught exception 'PhpAmqpLib\Exception\AMQPTimeoutException' with
message 'The connection timed out after 3 sec while awaiting incoming data' in
/home/directory/public_html/tracker/rabbit/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Wire/AMQPReader.php:132 Stack trace: #0 /home/directory/public_html/tracker/rabbit/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Wire/AMQPReader.php(149): PhpAmqpLib\Wire\AMQPReader->wait() #1 /home/directory/public_html/tracker/rabbit/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Wire/AMQPReader.php(106): PhpAmqpLib\Wire\AMQPReader->rawread(7) #2 /home/directory/public_html/tracker/rabbit/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php(530): PhpAmqpLib\Wire\AMQPReader->read(7) #3 /home/directory/public_html/tracker/rabbit/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php(578): PhpAmqpLib\Connection\AbstractConnection->wait in /home/directory/public_html/tracker/rabbit/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Wire/AMQPReader.php on line 132
```

**Comment by ramunasd** [comment]
@Pionell stack trace is still incomplete :) and this does not look like latest version...

**Comment by Pionell** [comment]
thats the whole stack trace, nothing more to show. I'll try updating.

**Comment by lukebakken** [comment]
> thats the whole stack trace, nothing more to show, try scrolling to the right. I'll try updating.

At which line of your code does the exception happen?

**Comment by Pionell** [comment]
this is the weird part - none of my code is "mentioned" in the fatal exception. I've included THE WHOLE page content that i'm getting, I've only replaced the directories to not include the domain name. I've checked the apache log and that seems to only show this code also, only difference being it includes the IP address of the caller.
