### ISSUE TITLE
Enabling heartbeat by default throws PHP Fatal error

### ISSUE THREAD

**Issue by ehsanmx** [php-amqplib/php-amqplib#699]
After updating to > v2.9.0, we are facing errors regarding heartbeat in our servers. here is the intriduced change https://github.com/php-amqplib/php-amqplib/pull/648#discussion_r288030125

Here is a stack trace of error:
```
run with `-v` to get more info about skipped or incomplete tests
PHP Fatal error:  Uncaught PhpAmqpLib\Exception\AMQPHeartbeatMissedException: Missed server heartbeat in /home/travis/build/demo/demo/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Wire/IO/AbstractIO.php:140
Stack trace:
#0 /home/travis/build/demo/demo/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Wire/IO/AbstractIO.php(83): PhpAmqpLib\Wire\IO\AbstractIO->check_heartbeat()
#1 /home/travis/build/demo/demo/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Wire/AMQPReader.php(134): PhpAmqpLib\Wire\IO\AbstractIO->select(NULL, 0)
#2 /home/travis/build/demo/demo/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Wire/AMQPReader.php(163): PhpAmqpLib\Wire\AMQPReader->wait()
#3 /home/travis/build/demo/demo/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Wire/AMQPReader.php(107): PhpAmqpLib\Wire\AMQPReader->rawread(7)
#4 /home/travis/build/demo/demo/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php(548): PhpAmqpLib\Wire\AMQPReader->read(7)
#5 /home/travis/build/spry in /home/travis/build/demo/demo/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Wire/IO/AbstractIO.php on line 140
```

**Comment by ramunasd** [comment]
This is because Your job takes much more time than configured heartbeat timeout. Just set higher  timeout value or disable it with 0.

**Comment by ehsanmx** [comment]
Yes, that's correct but it always took more than 60s but it never failed, we are considering this change as a BC break, do you?

**Comment by ehsanmx** [comment]
Update: We are going to fix this by own but changing default value is very fragile and can lead to a BC easily.
Thank you for your response @ramunasd
