### ISSUE TITLE
Fail to apply arguments to  queue_declare

### ISSUE THREAD

**Issue by symfonyluxury** [php-amqplib/php-amqplib#741]
I want to implement DXL, these are the codes below:
```
$args['x-dead-letter-exchange'] = 'dlx_exchange';
list($queue_name, ,) = $channel->queue_declare("", false, false, true, false, false, $args);
```
but I got errors:
```
Fatal error: Uncaught PhpAmqpLib\Exception\AMQPOutOfRangeException: AMQP-rabbit doesn't define data of type [] in /shared/httpd/cli/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Wire/AMQPAbstractCollection.php:420
Stack trace:
#0 /shared/httpd/cli/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Wire/AMQPWriter.php(425): PhpAmqpLib\Wire\AMQPAbstractCollection::getDataTypeForSymbol(NULL)
#1 /shared/httpd/cli/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Helper/Protocol/Protocol091.php(406): PhpAmqpLib\Wire\AMQPWriter->write_table(Array)
#2 /shared/httpd/cli/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Channel/AMQPChannel.php(674): PhpAmqpLib\Helper\Protocol\Protocol091->queueDeclare(0, '', false, false, true, false, false, Array)
#3 /shared/httpd/cli/rabbitmq/receive_logs_topic.php(10): PhpAmqpLib\Channel\AMQPChannel->queue_declare('', false, false, true, false, false, Array)
```

**Comment by symfonyluxury** [comment]
any idea? help plz

**Comment by ramunasd** [comment]
please take a look at `demo/delayed_message.php`

**Comment by symfonyluxury** [comment]
got it, thx
