### ISSUE TITLE
Amazon MQ amqp+ssl

### ISSUE THREAD

**Issue by rpogorelchuk** [php-amqplib/php-amqplib#757]
Trouble with connection to Amazon MQ (amqp+ssl)

```
$sslOptions = [
   'verify_peer' => false
];

$connection = new AMQPSSLConnection(
    'host.mq.us-west-1.amazonaws.com',
    5671,
    'user',
    'password', 
    '/',
    $sslOptions
);
```
Result:
```
php php-amqplib/demo/ssl_connection.php 
< [hex]: 
0000  41 4D 51 50 00 00 09 01                            AMQP.... 

waiting for 10,10
waiting for a new frame
closing input
closing socket
[18-Nov-2019 17:18:28 UTC] PHP Fatal error:  Uncaught PhpAmqpLib\Exception\AMQPInvalidFrameException: 
Invalid frame type 65 in /codebase/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php:567
```
PHP Version:
```
php -v
PHP 7.2.24 (cli) (built: Oct 25 2019 04:29:43) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.24, Copyright (c) 1999-2018, by Zend Technologies
```

**Comment by lukebakken** [comment]
What version of this library are you using?

The simplest explanation is that there is no TLS-enabled AMQP listener on port 5671. Please use [these steps](https://www.rabbitmq.com/troubleshooting-ssl.html) to diagnose.

We don't have access to your environment so we can't try to reproduce this issue.

Please also see the discussion in #437 

#758

**Comment by rpogorelchuk** [comment]
Amazon MQ uses AMQP 1.0 and this bundle uses 0.9.1
https://github.com/php-amqplib/RabbitMqBundle/issues/565
Thanks!

**Comment by mente** [comment]
Since November 2020 AmazonMQ supports AMQP 0.9.1

**Comment by DanielVillela** [comment]
trying with new 
`AMQPStreamConnection()` 
would not connect at all "/

and trying the way you used 
it worked for me!
```
$sslOptions = [
   'verify_peer' => false
];

$connection = new AMQPSSLConnection(
    'host.mq.us-west-1.amazonaws.com',
    5671,
    'user',
    'password', 
    '/',
    $sslOptions
);
```
works!!!

**I also used it to catch all errors:**
```
define('AMQP_DEBUG', true);
try {
}
catch (\Exception $e) {
     debug($e);
}
```

**Comment by speller** [comment]
I'm having the same issue with phpamqplib 3.2.0 connecting to Amazon MQ RabbitMQ. 

```php
                    AMQPSSLConnection::create_connection(
                        [
                            [
                                'host' => 'host',
                                'port' => 'port',
                                'user' => 'user',
                                'password' => 'password',
                                'vhost' => 'vhost',
                            ],
                        ],
                        [
                            'ssl_options' => [
                                'verify_peer' => false,
                            ],
                        ]
                    );
```

```none
< [hex]:
0000  41 4D 51 50 00 00 09 01                            AMQP....

waiting for 10,10
waiting for a new frame
> 10,10: Connection.start
Start from server, version: 0.9, properties: capabilities=(publisher_confirms=1, exchange_exchange_bindings=1, basic.nack=1, consumer_cancel_notify=1, connection.blocked=1, consumer_priorities=1, authentication_failure_close=1, per_consumer_qos=1, direct_reply_to=1), cluster_name=review_main, copyright=Copyright (c) 2007-2022 VMware, Inc. or its affiliates., information=Licensed under the MPL 2.0. Website: https://rabbitmq.com, platform=Erlang/OTP 24.3.3, product=RabbitMQ, version=3.8.30, mechanisms: AMQPLAIN, PLAIN, locales: en_US
< 10,11:: Connection.start_ok
< [hex]:
0000  01 00 00 00 00 01 3D 00  0A 00 0B 00 00 00 F5 07   ......=. ......�.
0010  70 72 6F 64 75 63 74 53  00 00 00 07 41 4D 51 50   productS ....AMQP
0020  4C 69 62 08 70 6C 61 74  66 6F 72 6D 53 00 00 00   Lib.plat formS...
0030  03 50 48 50 07 76 65 72  73 69 6F 6E 53 00 00 00   .PHP.ver sionS...
0040  05 33 2E 32 2E 30 0B 69  6E 66 6F 72 6D 61 74 69   .3.2.0.i nformati
0050  6F 6E 53 00 00 00 00 09  63 6F 70 79 72 69 67 68   onS..... copyrigh
0060  74 53 00 00 00 00 0C 63  61 70 61 62 69 6C 69 74   tS.....c apabilit
0070  69 65 73 46 00 00 00 8C  1C 61 75 74 68 65 6E 74   iesF...� .authent
0080  69 63 61 74 69 6F 6E 5F  66 61 69 6C 75 72 65 5F   ication_ failure_
0090  63 6C 6F 73 65 74 01 12  70 75 62 6C 69 73 68 65   closet.. publishe
00A0  72 5F 63 6F 6E 66 69 72  6D 73 74 01 16 63 6F 6E   r_confir mst..con
00B0  73 75 6D 65 72 5F 63 61  6E 63 65 6C 5F 6E 6F 74   sumer_ca ncel_not
00C0  69 66 79 74 01 1A 65 78  63 68 61 6E 67 65 5F 65   ifyt..ex change_e
00D0  78 63 68 61 6E 67 65 5F  62 69 6E 64 69 6E 67 73   xchange_ bindings
00E0  74 01 0A 62 61 73 69 63  2E 6E 61 63 6B 74 01 12   t..basic .nackt..
00F0  63 6F 6E 6E 65 63 74 69  6F 6E 2E 62 6C 6F 63 6B   connecti on.block
0100  65 64 74 01 08 41 4D 51  50 4C 41 49 4E 00 00 00   edt..AMQ PLAIN...
0110  2D 05 4C 4F 47 49 4E 53  00 00 00 04 72 6F 6F 74   -.LOGINS ....******
0120  08 50 41 53 53 57 4F 52  44 53 00 00 00 10 53 65   .PASSWOR DS....**
0130  63 72 65 74 53 65 63 72  65 74 31 32 33 34 05 65   **************.e
0140  6E 5F 55 53 CE                                     n_US�

< 10,11:: Connection.start_ok
waiting for 10,20, 10,30
waiting for a new frame
> 10,30: Connection.tune
< 10,31:: Connection.tune_ok
< [hex]:
0000  01 00 00 00 00 00 0C 00  0A 00 1F 07 FF 00 02 00   ........ ....�...
0010  00 00 00 CE                                        ...�

< 10,31:: Connection.tune_ok
< 10,40:: Connection.open
< [hex]:
0000  01 00 00 00 00 00 1B 00  0A 00 28 14 72 65 76 5F   ........ ..(.rev_
0010  62 69 64 5F 6D 32 5F 36  38 35 31 5F 63 6C 6F 75   bid_m2_6 851_clou
0020  00 00 CE                                           ..�

< 10,40:: Connection.open
waiting for 10,41
waiting for a new frame
> 10,41: Connection.open_ok
Open OK! known_hosts:
< [hex]:
0000  41 4D 51 50 00 00 09 01                            AMQP....

waiting for 10,10
waiting for a new frame
closing input
closing socket
PHP Fatal error:  Uncaught PhpAmqpLib\Exception\AMQPInvalidFrameException: Invalid frame type 21 in /magento/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php:600
Stack trace:
#0 /magento/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php(651): PhpAmqpLib\Connection\AbstractConnection->wait_frame(3)
#1 /magento/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Channel/AbstractChannel.php(235): PhpAmqpLib\Connection\AbstractConnection->wait_channel(0, 3)
#2 /magento/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Channel/AbstractChannel.php(352): PhpAmqpLib\Channel\AbstractChannel->next_frame(3)
#3 /magento/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php(264): PhpAmqpLib\Channel\AbstractChannel->wait(Array, false, 3)
#4 /magento/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php(236): PhpAmqpLib\Connection\AbstractConnection->connect()
#5 /magento/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Connection/AMQPStreamConnection.php(74): PhpAmqpLib in /magento/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php on line 600
```

The connection establishes and the lib authenticates and selects the vhost but then fails on the unknown frame.

How to solve that?

**Comment by ramunasd** [comment]
@speller What we see at this point is 2nd attempt to connect. It may happen only when older protocol version 0.8.0 is used, but this log clearly states you are using 0.9.1

It's very weird. Can You make sure your files are not malformed and there is no attempts to "fix something in live environment"?


```
> 10,41: Connection.open_ok
Open OK! known_hosts:
< [hex]:
0000  41 4D 51 50 00 00 09 01                            AMQP....
```

**Comment by speller** [comment]
@ramunasd that was my code issue, sorry for bothering you. I wanted to delete my comment but accidentally hid it and can't see the delete option anymore.

**Comment by romanbahniuk95** [comment]
> trying with new `AMQPStreamConnection()` would not connect at all "/
> 
> and trying the way you used it worked for me!
> 
> ```
> $sslOptions = [
>    'verify_peer' => false
> ];
> 
> $connection = new AMQPSSLConnection(
>     'host.mq.us-west-1.amazonaws.com',
>     5671,
>     'user',
>     'password', 
>     '/',
>     $sslOptions
> );
> ```
> 
> works!!!
> 
> **I also used it to catch all errors:**
> 
> ```
> define('AMQP_DEBUG', true);
> try {
> }
> catch (\Exception $e) {
>      debug($e);
> }
> ```

Thank you, help in 2024)
