### ISSUE TITLE
Unexpected heartbeat missed exception

### ISSUE THREAD

**Issue by thomasvargiu** [php-amqplib/php-amqplib#793]
**Version(s) affected**: 2.11.2

**Description**  
There is a BIG problem with the heartbeat, seems that it isn't handled correctly.
This doesn't happen on v.2.11.1.

**How to reproduce**  

```php
<?php

require 'vendor/autoload.php';

use PhpAmqpLib\Connection\AMQPStreamConnection;
use PhpAmqpLib\Message\AMQPMessage;

const HEARTBEAT = 2;

$connection = new AMQPStreamConnection(
    'rabbitmq',
    5672,
    'guest',
    'guest',
    '/',
    false,
    'AMQPLAIN',
    null,
    'en_US',
    20,
    20,
    null,
    false,
    HEARTBEAT
);
$channel = $connection->channel();

$count = 0;
while (true) {
    $count++;
    echo 'Publish ' . $count . PHP_EOL;

    $channel->basic_publish(new AMQPMessage('message ' . $count), '', 'foo');
    sleep(HEARTBEAT);
}

```

```
Publish 1
Publish 2
Publish 3
PHP Fatal error:  Uncaught PhpAmqpLib\Exception\AMQPHeartbeatMissedException: Missed server heartbeat in /var/www/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Wire/IO/AbstractIO.php:159
Stack trace:
#0 /var/www/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Wire/IO/StreamIO.php(223): PhpAmqpLib\Wire\IO\AbstractIO->checkBrokerHeartbeat()
#1 /var/www/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php(381): PhpAmqpLib\Wire\IO\StreamIO->write()
#2 /var/www/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php(427): PhpAmqpLib\Connection\AbstractConnection->write()
#3 /var/www/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Channel/AMQPChannel.php(1159): PhpAmqpLib\Connection\AbstractConnection->send_content()
#4 /var/www/test2.php(33): PhpAmqpLib\Channel\AMQPChannel->basic_publish()
#5 {main}
  thrown in /var/www/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Wire/IO/AbstractIO.php on line 159
```

**Comment by thomasvargiu** [comment]
I think the problem is here:

https://github.com/php-amqplib/php-amqplib/pull/791/files#diff-6873441dc17d577d2115e8f622a0a33dR153-R162

We are just checking `$last_read` nut we should also check `$last_write`.

**Comment by lukebakken** [comment]
You should be reading heartbeats from the server, however. We'll look into this. I'm checking how heartbeats are implemented in other libraries, like the Java client.

**Comment by thomasvargiu** [comment]
@lukebakken I tihnk other libraries are using threads to accomplish heartbeat, we can't.

**Comment by lukebakken** [comment]
I know that, I maintain those libraries :smile:

`basic_publish` should take some time to read data from the socket. The problem here may be that it isn't.

**Comment by ramunasd** [comment]
I will take care, thanks all.
