### ISSUE TITLE
Example Usage, PHP Fatal error:  Uncaught Error: Call to undefined method PhpAmqpLib\Message\AMQPMessage::ack

### ISSUE THREAD

**Issue by vkatochka** [php-amqplib/php-amqplib#805]
**Version(s) affected**: 3.8.5

**Description**  
Example https://github.com/php-amqplib/php-amqplib#usage. Tried to run demo/amqp_consumer.php, got error.

~~~
PHP Fatal error:  Uncaught Error: Call to undefined method PhpAmqpLib\Message\AMQPMessage::ack() in /vk/www/bsmng.me/tmp/amqplib/php-amqplib/demo/amqp_consumer.php:50
Stack trace:
#0 [internal function]: process_message(Object(PhpAmqpLib\Message\AMQPMessage))
#1 /vk/www/bsmng.me/tmp/amqplib/php-amqplib/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Channel/AMQPChannel.php(1033): call_user_func('process_message', Object(PhpAmqpLib\Message\AMQPMessage))
#2 [internal function]: PhpAmqpLib\Channel\AMQPChannel->basic_deliver(Object(PhpAmqpLib\Wire\AMQPReader), Object(PhpAmqpLib\Message\AMQPMessage))
#3 /vk/www/bsmng.me/tmp/amqplib/php-amqplib/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Channel/AbstractChannel.php(219): call_user_func(Array, Object(PhpAmqpLib\Wire\AMQPReader), Object(PhpAmqpLib\Message\AMQPMessage))
#4 /vk/www/bsmng.me/tmp/amqplib/php-amqplib/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Channel/AbstractChannel.php(374): PhpAmqpLib\Channel\AbstractChannel->dispatch('60,60', '\x08consumer\x00\x00\x00\x00\x00\x00...', Object(Php in /vk/www/bsmng.me/tmp/amqplib/php-amqplib/demo/amqp_consumer.php on line 50
~~~

**Comment by ramunasd** [comment]
please refer to latest stable demo https://github.com/php-amqplib/php-amqplib/blob/v2.11.3/demo/amqp_consumer.php

a new interface isn't released yet
