### ISSUE TITLE
Allow Reconnect with Broken pipe or closed connection

### ISSUE THREAD

**Issue by sujit-baniya** [php-amqplib/php-amqplib#889]
Latest version

```php
message=PhpAmqpLib\Exception\AMQPConnectionClosedException: Broken pipe or closed connection in /application/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Wire/IO/StreamIO.php:233
Stack trace:
#0 /application/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php(388): PhpAmqpLib\Wire\IO\StreamIO->write('\x01\x00\x00\x00\x00\x00\v\x00\n\x002\x00\x00\x00\x00...')
#1 /application/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php(516): PhpAmqpLib\Connection\AbstractConnection->write('\x01\x00\x00\x00\x00\x00\v\x00\n\x002\x00\x00\x00\x00...')
#2 /application/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Channel/AbstractChannel.php(247): PhpAmqpLib\Connection\AbstractConnection->send_channel_method_frame(0, Array, Object(PhpAmqpLib\Wire\AMQPWriter))
#3 /application/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php(724): PhpAmqpLib\Channel\AbstractChannel->send_method_frame(Array, Object(PhpAmqpLib\Wire\AMQPWriter))
#4 /application/vendor/intergo/rabbit-queue/src/Queue/RabbitMQQueue.php(595): PhpAmqpLib\Connection\AbstractConnection->close()
#5 /application/vendor/intergo/rabbit-queue/src/Queue/Connectors/RabbitMQConnector.php(59): Intergo\RabbitQueue\Queue\RabbitMQQueue->close()
#6 /application/vendor/illuminate/events/Dispatcher.php(369): Intergo\RabbitQueue\Queue\Connectors\RabbitMQConnector::Intergo\RabbitQueue\Queue\Connectors\{closure}(Object(Illuminate\Queue\Events\WorkerStopping))
#7 /application/vendor/illuminate/events/Dispatcher.php(218): Illuminate\Events\Dispatcher->Illuminate\Events\{closure}('Illuminate\\Queu...', Array)
#8 /application/vendor/illuminate/queue/Worker.php(602): Illuminate\Events\Dispatcher->dispatch('Illuminate\\Queu...')
#9 /application/vendor/intergo/rabbit-queue/src/Consumer.php(173): Illuminate\Queue\Worker->stop(0)
#10 /application/vendor/illuminate/queue/Worker.php(239): Intergo\RabbitQueue\Consumer->stop()
#11 /application/vendor/intergo/rabbit-queue/src/Consumer.php(142): Illuminate\Queue\Worker->stopIfNecessary(Object(Illuminate\Queue\WorkerOptions), NULL, NULL)
#12 /application/vendor/illuminate/queue/Console/WorkCommand.php(112): 
```

How can I reconnect in above case

**Comment by ramunasd** [comment]
Please use discussions or mailing list for questions.

**Comment by dmitryuk** [comment]
https://github.com/php-amqplib/php-amqplib/discussions/935
