### ISSUE TITLE
Consumer fails with AMQP-rabbit doesn't define data of type [d]

### ISSUE THREAD

**Issue by stepanets** [php-amqplib/php-amqplib#924]
**Version(s) affected**: 2.12.3

**Description**  
Consumer fails when trying to create message from data

```
PhpAmqpLib\Exception\AMQPOutOfRangeException: AMQP-rabbit doesn't define data of type [d]
#18 home/backend/www/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Wire/AMQPAbstractCollection.php(464): PhpAmqpLib\Wire\AMQPAbstractCollection::getDataTypeForSymbol
#17 home/backend/www/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Wire/AMQPReader.php(419): PhpAmqpLib\Wire\AMQPReader::read_table
#16 home/backend/www/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Wire/AMQPReader.php(432): PhpAmqpLib\Wire\AMQPReader::read_table_object
#15 home/backend/www/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Message/AMQPMessage.php(480): PhpAmqpLib\Message\AMQPMessage::load_properties
#14 home/backend/www/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Channel/AbstractChannel.php(299): PhpAmqpLib\Channel\AbstractChannel::createMessage
#13 home/backend/www/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Channel/AbstractChannel.php(284): PhpAmqpLib\Channel\AbstractChannel::wait_content
#12 home/backend/www/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Channel/AbstractChannel.php(518): PhpAmqpLib\Channel\AbstractChannel::maybe_wait_for_content
#11 home/backend/www/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Channel/AbstractChannel.php(371): PhpAmqpLib\Channel\AbstractChannel::wait
#10 home/backend/www/vendor/mikemadisonweb/yii2-rabbitmq/components/Consumer.php(220): mikemadisonweb\rabbitmq\components\Consumer::consume
#9 home/backend/www/vendor/mikemadisonweb/yii2-rabbitmq/controllers/RabbitMQController.php(106): mikemadisonweb\rabbitmq\controllers\RabbitMQController::actionConsume
#8 [internal](0): call_user_func_array
#7 home/backend/www/vendor/yiisoft/yii2/base/InlineAction.php(57): yii\base\InlineAction::runWithParams
#6 home/backend/www/vendor/yiisoft/yii2/base/Controller.php(181): yii\base\Controller::runAction
#5 home/backend/www/vendor/yiisoft/yii2/console/Controller.php(184): yii\console\Controller::runAction
#4 home/backend/www/vendor/yiisoft/yii2/base/Module.php(534): yii\base\Module::runAction
#3 home/backend/www/vendor/yiisoft/yii2/console/Application.php(181): yii\console\Application::runAction
#2 home/backend/www/vendor/yiisoft/yii2/console/Application.php(148): yii\console\Application::handleRequest
#1 home/backend/www/vendor/yiisoft/yii2/base/Application.php(392): yii\base\Application::run
#0 home/backend/www/yii(34): null
```

We have many consumers based on this library, but the problem is only with one of them. And this is a float bug.

**How to reproduce**  
Cant reproduce on local.

**Possible Solution**  
This is the slowest consumer in project, can it be the reason?

**Additional context**  
![изображение](https://user-images.githubusercontent.com/2420662/122874735-87481700-d35d-11eb-9372-c726f19963ac.png)

Queue details:
```
x-dead-letter-exchange: in_dlx
x-dead-letter-routing-key:  make_agreement
durable: true
```

**Comment by stepanets** [comment]
## Solved

There were 4 "broken" messages in the queue, which put down consumers and return back to the queue head. How they could have broken remains a mystery.

**Comment by stepanets** [comment]
I have investigate this problem more carefully, and I found that messages were not broken. They were published by https://github.com/streadway/amqp golang library. It use data type of `d` for `float64`.

And this is official data types for headers table:
```
field-value = 't' boolean
            / 'b' short-short-int
            / 'B' short-short-uint
            / 'U' short-int
            / 'u' short-uint
            / 'I' long-int
            / 'i' long-uint
            / 'L' long-long-int
            / 'l' long-long-uint
            / 'f' float
            / 'd' double
            / 'D' decimal-value
            / 's' short-string
            / 'S' long-string
            / 'A' field-array
            / 'T' timestamp
            / 'F' field-table
            / 'V' ; no field
```

**Comment by ramunasd** [comment]
@stepanets looks like You found a bug. This library always encodes floats to strings at least since 2014. And numeric strings are decoded back to strings :|  Perhaps RabbitMQ did not support all data types and there was some workarounds made specifically for it.

I see that proper fix would introduce breaking change. I need to check whether all referenced data types are supported by RabbitMQ and since when.

Data type table for reference:
https://www.rabbitmq.com/amqp-0-9-1-errata.html

**Comment by ArkinHp** [comment]
i got the error again  in 2.6 version , for x-delay-exchange, how this happen
